import { describe, expect, it } from 'vitest'
import { generatePrecastGirderCandidates, generateSteelGirderCandidates, precastSectionProperties, steelSectionProperties } from './girderCandidates'
const material={domainType:'StructuralSteelMaterial' as const,id:'S355',name:'S355',properties:{}}
describe('girder candidates',()=>{
 it('calculates finite positive canonical precast properties and updates with geometry',()=>{const a=precastSectionProperties({H:1,Btf:1,Bbf:.5,tw:.25,th1:.15,bh1:.1,bh2:.2,th2:.3});const b=precastSectionProperties({H:2.8,Btf:1,Bbf:.6,tw:.25,th1:.15,bh1:.1,bh2:.2,th2:.3});expect(Object.values(a).every(Number.isFinite)).toBe(true);expect(Object.values(a).every(v=>v>0)).toBe(true);expect(b.A).not.toBe(a.A)})
 it('attaches precast properties to every generated candidate',()=>{const r=generatePrecastGirderCandidates({geometry:{H:2.8,Btf:1,Bbf:.6,tw:.25,th1:.15,bh1:.1,bh2:.2,th2:.3},material:{domainType:'ConcreteMaterial',id:'C40/50',name:'C40/50',properties:{}}});expect((r.candidates[0].sectionProperties as any)?.A).toBeGreaterThan(0)})
 it('calculates the welded steel section independently of material properties',()=>{const p=steelSectionProperties({H:2.5,Btf:.8,ttf:.04,Bbf:.9,tbf:.05,tw:.02});expect(p.hw).toBeCloseTo(2.41);expect(p.area).toBeCloseTo(.1252);expect(p.massStatus).toBe('INCOMPLETE')})
 it('generates deterministic Cartesian steel candidates and rejects invalid hw',()=>{const r=generateSteelGirderCandidates({H:[2,2.5,3],Btf:[.6,.8],ttf:.04,Bbf:[.7,.9],tbf:.05,tw:.02,material});expect(r.candidates).toHaveLength(12);expect(r.candidates.map(x=>x.id)).toEqual(generateSteelGirderCandidates({H:[2,2.5,3],Btf:[.6,.8],ttf:.04,Bbf:[.7,.9],tbf:.05,tw:.02,material}).candidates.map(x=>x.id));const invalid=generateSteelGirderCandidates({H:.05,Btf:.8,ttf:.04,Bbf:.9,tbf:.04,tw:.02,material});expect(invalid.candidates).toHaveLength(0);expect(invalid.invalidCombinations).toBe(1)})
 it('calculates the asymmetric default section independently of material density',()=>{const r=generateSteelGirderCandidates({H:2.5,Btf:.8,ttf:.04,Bbf:.9,tbf:.05,tw:.02,material});const p=r.candidates[0].sectionProperties as any;expect(p.hw).toBeCloseTo(2.41);expect(p.area).toBeCloseTo(.1252);expect(p.centroidY).toBeCloseTo(1.126,3);expect(p.Ix).toBeGreaterThan(0);expect(p.Iy).toBeGreaterThan(0);expect(p.WxTop).not.toBe(p.WxBottom);expect(p.massStatus).toBe('INCOMPLETE')})
})
