import type { MaterialValue } from './types'
import { normalizeCandidateInput, type LengthInput } from './pierCandidates'

export type GirderType = 'PRECAST' | 'STEEL'
export interface SteelSectionProperties { area:number; centroidY:number; Ix:number; Iy:number; WxTop:number; WxBottom:number; Wy:number; hw:number; massPerLength?:number; selfWeightPerLength?:number; massStatus:'VALID'|'INCOMPLETE'; selfWeightStatus:'VALID'|'INCOMPLETE' }
export interface GirderCandidate { id:string; familyId:string; girderType:GirderType; sectionType:string; geometry:Record<string,number>; material:MaterialValue; preferredSpan:number; applicableSpanRange:{min:number;max:number}; sectionProperties?:SteelSectionProperties; validationStatus:'VALID'|'INCOMPLETE' }
export interface GirderGenerationResult { candidates:GirderCandidate[]; generatedCombinations:number; invalidCombinations:number }
const MAX=10000
const values=(input:LengthInput|number|number[])=>normalizeCandidateInput(input,'girder').map(Number)
const cartesian=(fields:{key:string;values:number[]}[])=>{const total=fields.reduce((n,f)=>n*f.values.length,1);if(total>MAX)throw new Error(`Maximum is ${MAX} girder combinations.`);const out:Record<string,number>[]=[];const walk=(i: number,row:Record<string,number>)=>{if(i===fields.length){out.push({...row});return}for(const v of fields[i].values)walk(i+1,{...row,[fields[i].key]:v})};walk(0,{});return out}
export function steelSectionProperties(g:Record<string,number>, density?:number):SteelSectionProperties { const {H,Btf,ttf,Bbf,tbf,tw}=g,hw=H-ttf-tbf; if(hw<=0) return {area:0,centroidY:0,Ix:0,Iy:0,WxTop:0,WxBottom:0,Wy:0,hw,massStatus:'INCOMPLETE',selfWeightStatus:'INCOMPLETE'}; const parts=[{a:Bbf*tbf,y:tbf/2,b:Bbf,h:tbf},{a:tw*hw,y:tbf+hw/2,b:tw,h:hw},{a:Btf*ttf,y:tbf+hw+ttf/2,b:Btf,h:ttf}],area=parts.reduce((s,p)=>s+p.a,0),cy=parts.reduce((s,p)=>s+p.a*p.y,0)/area; const Ix=parts.reduce((s,p)=>s+(p.b*p.h**3)/12+p.a*(p.y-cy)**2,0),Iy=parts.reduce((s,p)=>s+(p.h*p.b**3)/12,0), mass=density===undefined?undefined:area*density; return {area,centroidY:cy,Ix,Iy,WxTop:Ix/(H-cy),WxBottom:Ix/cy,Wy:Iy/(Math.max(Btf,Bbf)/2),hw,massPerLength:mass,selfWeightPerLength:mass===undefined?undefined:mass*9.80665/1000,massStatus:mass===undefined?'INCOMPLETE':'VALID',selfWeightStatus:mass===undefined?'INCOMPLETE':'VALID'} }
export function generateSteelGirderCandidates(input:{H:LengthInput;Btf:LengthInput;ttf:LengthInput;Bbf:LengthInput;tbf:LengthInput;tw:LengthInput;material:MaterialValue;familyId?:string;preferredSpan?:number;minSpan?:number;maxSpan?:number},maxCandidates=MAX):GirderGenerationResult { const fields=Object.entries(input).filter(([key])=>['H','Btf','ttf','Bbf','tbf','tw'].includes(key)).map(([key,value])=>({key,values:values(value as LengthInput)})); const rows=cartesian(fields); if(rows.length>maxCandidates)throw new Error(`Maximum is ${maxCandidates} girder combinations.`);let invalid=0;const candidates=rows.flatMap(g=>{const props=steelSectionProperties(g);if(props.hw<=0){invalid++;return[]}const id=`steel-${Object.values(g).map(v=>v.toFixed(6)).join('-')}`;return [{id,familyId:input.familyId??'SG-01',girderType:'STEEL' as const,sectionType:'WELDED_I',geometry:g,material:input.material,preferredSpan:input.preferredSpan??0,applicableSpanRange:{min:input.minSpan??0,max:input.maxSpan??0},sectionProperties:props,validationStatus:(props.massStatus==='VALID'?'VALID':'INCOMPLETE') as 'VALID'|'INCOMPLETE'}]});return {candidates,generatedCombinations:rows.length,invalidCombinations:invalid} }
export function generatePrecastGirderCandidates(input:{geometry:Record<string,LengthInput>;material:MaterialValue;familyId?:string;preferredSpan?:number;minSpan?:number;maxSpan?:number}):GirderGenerationResult {const fields=Object.entries(input.geometry).map(([key,value])=>({key,values:values(value)})),rows=cartesian(fields);const candidates=rows.map(g=>({id:`precast-${Object.values(g).map(v=>v.toFixed(6)).join('-')}`,familyId:input.familyId??'PG-200',girderType:'PRECAST' as const,sectionType:'I_GIRDER',geometry:g,material:input.material,preferredSpan:input.preferredSpan??0,applicableSpanRange:{min:input.minSpan??0,max:input.maxSpan??0},validationStatus:'VALID' as const}));return {candidates,generatedCombinations:rows.length,invalidCombinations:0}}

