export const FAMILY_UI_TOKENS = {
  fontFamily: 'Segoe UI, system-ui, sans-serif',
  nodeTitleFontSize: 16,
  nodeTitleFontWeight: 600,
  panelTitleFontSize: 12,
  panelTitleFontWeight: 600,
  tableFontSize: 12,
  tableRowHeight: 30,
  panelRadius: 6,
  panelPadding: 12,
  panelPaddingTop: 10,
  panelPaddingX: 12,
  headingContentGap: 10,
  searchWidth: 340,
  searchTableGap: 10,
  panelGap: 12,
  libraryRatio: 1,
  centerRatio: 3,
  resultsRatio: 4,
} as const
