export const TECHNICAL_DRAWING_TOKENS = {
  fontFamily: 'Segoe UI, sans-serif',
  fontSize: 12,
  fontWeight: 400,
  technicalDimensionColor: '#9FAEC6',
  textColor: '#9FAEC6',
  dimensionColor: '#9FAEC6',
  extensionColor: '#9FAEC6',
  strokeWidth: 1,
  arrowLength: 8.8,
  arrowWidth: 4.4,
  arrowSize: 6,
  extensionGap: 4,
  extensionOverrun: 3,
  dimensionTextGap: 8,
  textGap: 8,
  baseOffset: 0,
  laneGap: 16,
} as const
