export const TECHNICAL_DRAWING_TOKENS = {
  fontFamily: 'Segoe UI, sans-serif',
  fontSize: 12,
  visualScaleFactor: 2,
  fontWeight: 400,
  technicalDimensionColor: '#9FAEC6',
  textColor: '#9FAEC6',
  dimensionColor: '#9FAEC6',
  extensionColor: '#9FAEC6',
  strokeWidth: 1,
  arrowLength: 4.4,
  arrowWidth: 2.2,
  arrowSize: 3,
  extensionGap: 4,
  extensionOverrun: 3,
  dimensionTextGap: 8,
  textGap: 8,
  baseOffset: 0,
  laneGap: 16,
} as const
