export type RecentAccessMode = 'handle' | 'metadata-only'
export type RecentProject = { id:string; projectName:string; fileName:string; lastUsedAt:string; handle?:FileSystemFileHandle; available:boolean; accessMode?:string }
export type RecentAccessFailure = 'HANDLE_MISSING'|'PERMISSION_DENIED'|'FILE_UNAVAILABLE'
export class RecentProjectAccessError extends Error { readonly code:RecentAccessFailure; constructor(code:RecentAccessFailure,message:string){super(message);this.code=code;this.name='RecentProjectAccessError'} }
export const MAX_RECENT_PROJECTS=5
const DB_NAME='kopruq-project-files',STORE='recent-projects',META_KEY='kopruq.recent-projects.metadata.v1',sessionHandles=new Map<string,FileSystemFileHandle>()
const detail=(error:unknown)=>error instanceof DOMException?(error.name==='AbortError'?'cancelled':error.name):error instanceof Error?(error.message||error.name):String(error)
function metadata():RecentProject[]{try{const value=JSON.parse(localStorage.getItem(META_KEY)??'[]');return Array.isArray(value)?value.map((item):RecentProject=>{const handle=sessionHandles.get(item.id);return {...item,handle,available:Boolean(handle),accessMode:handle?'handle':'metadata-only'}}).sort((a,b)=>b.lastUsedAt.localeCompare(a.lastUsedAt)):[]}catch{return[]}}
function saveMetadata(items:RecentProject[]){try{localStorage.setItem(META_KEY,JSON.stringify(items.map(({handle:_handle,...item})=>({...item,accessMode:item.accessMode??'metadata-only'}))))}catch{}}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB is unavailable.'));const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error??new Error('Unable to open Recent Projects storage.'))})}
function readAll(db:IDBDatabase):Promise<RecentProject[]>{return new Promise((resolve,reject)=>{const request=db.transaction(STORE,'readonly').objectStore(STORE).getAll();request.onsuccess=()=>resolve((request.result as RecentProject[]).map((item):RecentProject=>{const handle=item.handle??sessionHandles.get(item.id);if(handle)sessionHandles.set(item.id,handle);return {...item,handle,available:Boolean(handle),accessMode:handle?'handle':'metadata-only'}}).sort((a,b)=>b.lastUsedAt.localeCompare(a.lastUsedAt)));request.onerror=()=>reject(request.error)})}
export async function listRecentProjects(){try{const db=await openDb();const records=await readAll(db);db.close();const recent=records.slice(0,MAX_RECENT_PROJECTS),stale=records.slice(MAX_RECENT_PROJECTS);if(stale.length){const cleanup=await openDb();await new Promise<void>((resolve,reject)=>{const tx=cleanup.transaction(STORE,'readwrite'),store=tx.objectStore(STORE);stale.forEach(record=>store.delete(record.id));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});cleanup.close()}saveMetadata(recent);return recent}catch{const recent=metadata().slice(0,MAX_RECENT_PROJECTS);saveMetadata(recent);return recent}}
export async function rememberRecentProject(projectName:string,fileName:string,handle?:FileSystemFileHandle){const id=fileName;if(handle)sessionHandles.set(id,handle);const item={id,projectName,fileName,lastUsedAt:new Date().toISOString()};try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE),request=store.get(id);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const previous=request.result as RecentProject|undefined,retained=handle??previous?.handle??sessionHandles.get(id);if(retained)sessionHandles.set(id,retained);const merged:RecentProject={...previous,...item,handle:retained,available:Boolean(retained),accessMode:retained?'handle':'metadata-only'},put=store.put(merged);put.onerror=()=>reject(put.error)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}catch{const previous=metadata().find(record=>record.id===id),retained=handle??previous?.handle??sessionHandles.get(id);if(retained)sessionHandles.set(id,retained);saveMetadata([{...previous,...item,handle:retained,available:Boolean(retained),accessMode:retained?'handle':'metadata-only'},...metadata().filter(record=>record.id!==id)].slice(0,MAX_RECENT_PROJECTS))}return listRecentProjects()}
export async function repairRecentProject(entry:RecentProject,handle:FileSystemFileHandle){sessionHandles.set(entry.id,handle);return rememberRecentProject(entry.projectName,handle.name,handle)}
export async function getRecentProjectFile(entry:RecentProject){const handle=entry.handle??sessionHandles.get(entry.id);if(!handle)throw new RecentProjectAccessError('HANDLE_MISSING','Bu dosya için kayıtlı dosya erişimi bulunamadı.');const candidate=handle as FileSystemFileHandle&{queryPermission?:(options:{mode:'read'})=>Promise<PermissionState>;requestPermission?:(options:{mode:'read'})=>Promise<PermissionState>};try{const permission=candidate.queryPermission?await candidate.queryPermission({mode:'read'}):'prompt';if(permission==='denied')throw new RecentProjectAccessError('PERMISSION_DENIED','permission denied: Bu dosyaya erişim izni verilmedi.');if(permission==='prompt'){const granted=candidate.requestPermission?await candidate.requestPermission({mode:'read'}):'denied';if(granted!=='granted')throw new RecentProjectAccessError('PERMISSION_DENIED','permission denied: Bu dosyaya erişim izni verilmedi.')}return await handle.getFile()}catch(error){if(error instanceof RecentProjectAccessError)throw error;throw new RecentProjectAccessError('FILE_UNAVAILABLE',`Dosyaya erişilemiyor. Dosya taşınmış, silinmiş veya erişim dışı olabilir. ${detail(error)}`)}}
