import { beforeEach, describe, expect, it, vi } from 'vitest'
import { getRecentProjectFile, listRecentProjects, rememberRecentProject } from './recentProjects'

beforeEach(() => { localStorage.clear(); vi.restoreAllMocks() })
const handle = (permission: PermissionState = 'granted', file = new File(['{}'], 'project.kopruq')) => ({ queryPermission: vi.fn().mockResolvedValue(permission), requestPermission: vi.fn().mockResolvedValue('granted'), getFile: vi.fn().mockResolvedValue(file) }) as unknown as FileSystemFileHandle

describe('Recent Projects repository', () => {
  it('creates a metadata record and reads it back', async () => { const records = await rememberRecentProject('Bridge', 'Bridge.kopruq', handle()); expect(records[0].projectName).toBe('Bridge'); expect(records[0].fileName).toBe('Bridge.kopruq') })
  it('keeps at most five records and newest first', async () => { for (let i = 0; i < 6; i++) await rememberRecentProject(`P${i}`, `P${i}.kopruq`, handle()); const records = await listRecentProjects(); expect(records).toHaveLength(5); expect(records[0].fileName).toBe('P5.kopruq'); expect(records.some((item) => item.fileName === 'P0.kopruq')).toBe(false) })
  it('removes legacy overflow records when the repository is read', async () => { Object.defineProperty(window, 'indexedDB', { configurable: true, value: undefined }); localStorage.setItem('kopruq.recent-projects.metadata.v1', JSON.stringify(Array.from({ length: 7 }, (_, i) => ({ id: `old-${i}`, projectName: `P${i}`, fileName: `P${i}.kopruq`, lastUsedAt: new Date(2026, 0, i + 1).toISOString(), available: false })))); const records = await listRecentProjects(); expect(records).toHaveLength(5); expect(JSON.parse(localStorage.getItem('kopruq.recent-projects.metadata.v1') ?? '[]')).toHaveLength(5) })
  it('updates metadata for the same file identity in fallback storage', async () => { Object.defineProperty(window, 'indexedDB', { configurable: true, value: undefined }); await rememberRecentProject('Old', 'same.kopruq'); await rememberRecentProject('New', 'same.kopruq'); const records = await listRecentProjects(); expect(records.filter((item) => item.fileName === 'same.kopruq')).toHaveLength(1); expect(records[0].projectName).toBe('New') })
  it('uses metadata fallback when IndexedDB is unavailable', async () => { Object.defineProperty(window, 'indexedDB', { configurable: true, value: undefined }); await rememberRecentProject('Fallback', 'fallback.kopruq'); expect((await listRecentProjects())[0].available).toBe(false) })
  it('does not duplicate a file and moves it to the top when reused', async () => { Object.defineProperty(window, 'indexedDB', { configurable: true, value: undefined }); await rememberRecentProject('First', 'first.kopruq'); await rememberRecentProject('Second', 'second.kopruq'); await rememberRecentProject('First Updated', 'first.kopruq'); const records = await listRecentProjects(); expect(records.filter((item) => item.fileName === 'first.kopruq')).toHaveLength(1); expect(records[0].fileName).toBe('first.kopruq'); expect(records[0].projectName).toBe('First Updated') })
  it('preserves independent handles for five records when another record is updated', async () => { Object.defineProperty(window, 'indexedDB', { configurable: true, value: undefined }); const handles = ['A', 'B', 'C', 'D', 'E'].map((name) => ({ token: name }) as unknown as FileSystemFileHandle); for (let i = 0; i < handles.length; i++) await rememberRecentProject(String.fromCharCode(65 + i), `${String.fromCharCode(65 + i)}.kopruq`, handles[i]); await rememberRecentProject('B updated', 'B.kopruq'); const records = await listRecentProjects(); expect(records).toHaveLength(5); expect(records.find((record) => record.fileName === 'B.kopruq')?.projectName).toBe('B updated') })
  it('reads a granted file handle', async () => { const entry = { id: 'x', projectName: 'P', fileName: 'p.kopruq', lastUsedAt: new Date().toISOString(), available: true, handle: handle() }; expect(await getRecentProjectFile(entry)).toBeInstanceOf(File) })
  it('requests permission for a prompt handle', async () => { const h = handle('prompt') as FileSystemFileHandle & { requestPermission: ReturnType<typeof vi.fn> }; const entry = { id: 'x', projectName: 'P', fileName: 'p.kopruq', lastUsedAt: '', available: true, handle: h }; await getRecentProjectFile(entry); expect(h.requestPermission).toHaveBeenCalled() })
  it('rejects denied permission and cancelled permission', async () => { const denied = { id: 'x', projectName: 'P', fileName: 'p.kopruq', lastUsedAt: '', available: true, handle: handle('denied') }; await expect(getRecentProjectFile(denied)).rejects.toThrow('permission'); const cancelled = handle('prompt') as FileSystemFileHandle & { requestPermission: ReturnType<typeof vi.fn> }; cancelled.requestPermission.mockRejectedValue(new DOMException('cancelled', 'AbortError')); await expect(getRecentProjectFile({ ...denied, handle: cancelled })).rejects.toThrow('cancelled') })
  it('propagates missing, moved and unreadable file errors', async () => { const h = handle(); (h.getFile as ReturnType<typeof vi.fn>).mockRejectedValue(new DOMException('NotFound', 'NotFoundError')); await expect(getRecentProjectFile({ id: 'x', projectName: 'P', fileName: 'p.kopruq', lastUsedAt: '', available: true, handle: h })).rejects.toThrow('NotFound') })
})
