import type { FamilyAlternative } from '../../graph/family/familyResults'
import type { ProjectUnits } from '../../graph/domain/quantities'
import { cellValue, filterFamilyCandidates, paginateAlternatives } from '../model/graphFamilyPresentation'

type Column = { key: string; label: string }
type Props = { rows: readonly FamilyAlternative[]; columns: readonly Column[]; units: ProjectUnits; displayIds: ReadonlyMap<string, string>; selectedId?: string; query: string; page: number; size: number; sort?: { key: string; direction: 'asc' | 'desc' }; onQuery: (value: string) => void; onPage: (value: number) => void; onSize: (value: number) => void; onSort: (key: string) => void; onSelect: (id: string) => void }
export default function CandidateSectionsPanel({ rows, columns, units, displayIds, selectedId, query, page, size, sort, onQuery, onPage, onSize, onSort, onSelect }: Props) {
  const filtered = filterFamilyCandidates(rows, columns, query, units, displayIds), paged = paginateAlternatives(filtered, page, size)
  return <section className="family-candidate-table" data-testid="family-candidate-sections-panel"><header><h2>CANDIDATE SECTIONS ({rows.length})</h2><input aria-label="Search candidates" placeholder="Search candidates..." value={query} onChange={event => onQuery(event.target.value)} /></header><div className="spn-family-table-scroll"><table className="spn-table spn-family-candidate-table"><thead><tr>{columns.map(column => <th key={column.key}><button type="button" onClick={() => onSort(column.key)}>{column.label}{sort?.key === column.key ? (sort.direction === 'asc' ? ' ↑' : ' ↓') : ''}</button></th>)}</tr></thead><tbody>{paged.items.map(row => <tr key={row.candidateId} className={row.candidateId === selectedId ? 'spn-row-selected' : ''} onClick={() => onSelect(row.candidateId)}>{columns.map(column => <td key={column.key}>{cellValue(row, column.key, units, displayIds)}</td>)}</tr>)}</tbody></table></div><footer className="spn-family-pagination"><span>Showing {paged.start}–{paged.end} of {paged.total}</span><select aria-label="Page size" value={size} onChange={event => { onSize(Number(event.target.value)); onPage(1) }}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select><button type="button" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><button type="button" disabled={page >= paged.pageCount} onClick={() => onPage(page + 1)}>Next</button></footer></section>
}
