import type { ReactNode } from 'react'
import { getNodeDefinitions, type NodeDefinition } from '../../graph/registry/nodeRegistry'
import { getNodeLogo } from '../../graph/registry/nodeLogos'
import type { GraphRunValidity } from '../../graph/family/graphRunValidity'
import { getActiveGraph } from '../../graph/state/graphStore'
import { graphRunValidity } from '../../graph/family/graphRunValidity'
export function structuralFamilyItems() { return getNodeDefinitions().filter(item => item.category === 'STRUCTURAL_FAMILY' && item.type !== 'structural.span_arrangement' && item.type !== 'structural.assembly') }
export function StructuralFamilyLibrary({ selectedType, onSelect, validity = graphRunValidity(getActiveGraph()) }: { selectedType: string; onSelect: (item: NodeDefinition) => void; validity?: GraphRunValidity }) { return <aside className="family-structural-library" aria-label="Family Library" data-testid="family-library-region" data-family-region="library"><h2>STRUCTURAL FAMILY LIBRARY</h2><div className={`family-graph-validity family-graph-validity--${validity.toLowerCase()}`}>{validity}</div><div className="family-structural-library-scroll">{structuralFamilyItems().map(item => <button type="button" key={item.type} className={item.type === selectedType ? 'active' : ''} onClick={() => onSelect(item)} title={item.description}><img src={getNodeLogo(item.type)} alt="" /><span>{item.label}</span></button>)}</div></aside> }
export function FamilyPanel({ title, children, className = '', panel }: { title: string; children: ReactNode; className?: string; panel?: string }) { const testId = className.includes('parameters') ? 'family-parameters-panel' : className.includes('section-preview') ? 'family-preview-panel' : className.includes('properties') ? 'family-properties-panel' : undefined; return <section className={`family-panel ${className}`} data-testid={testId} data-family-panel={panel}><h2>{title}</h2>{children}</section> }
