import { useEffect, useRef, useState } from 'react'
import type { FamilyAlternative } from '../../graph/family/familyResults'
import { formatDisplayValue, toDisplayValue, type ProjectUnits } from '../../graph/domain/quantities'
import { readProjectState } from '../../project/model/projectWorkspace'
import { PRECAST_GIRDER_DIMENSION_PRESET as P } from '../model/precastGirderDimensionPreset'
import { HorizontalDimension } from '../../../shared/technical-drawing/components/HorizontalDimension'
import { VerticalDimension } from '../../../shared/technical-drawing/components/VerticalDimension'
import { InlineDimension } from '../../../shared/technical-drawing/components/InlineDimension'
import { resolveHorizontalDimension, resolveInlineDimension, resolveVerticalDimension, dimensionExtensionLine } from '../../../shared/technical-drawing/DimensionGeometry'
import { precastSectionProperties } from '../../graph/domain/girderCandidates'
import { drawingBounds } from '../../../shared/technical-drawing/DrawingBounds'
import { formatTechnicalDimension } from '../../../shared/technical-drawing/DimensionFormatter'
type Props={candidate:FamilyAlternative;familyCandidates?:readonly FamilyAlternative[];projectUnits?:ProjectUnits;displayId?:string;showDetails?:boolean;onSelectCandidate?:(id:string)=>void}
type G={H:number;Btf:number;Bbf:number;tw:number;th1:number;bh1:number;bh2:number;th2:number}
const scalar=(value:unknown):number|undefined=>{if(typeof value==='number')return Number.isFinite(value)?value:undefined;if(typeof value==='object'&&value!==null&&'value' in value&&typeof (value as {value?:unknown}).value==='number')return Number.isFinite((value as {value:number}).value)?(value as {value:number}).value:undefined;return undefined}
export function canonicalPrecastParameters(candidate:FamilyAlternative):G|undefined{const data=candidate.candidateData as Record<string,unknown>;const source=((data.geometry??data.parameters??data.values??{}) as Record<string,unknown>);const n=(keys:string[])=>keys.map(key=>scalar(source[key])).find((value):value is number=>value!==undefined);const [H,Btf,Bbf,tw,th1,bh1,bh2,th2]=[n(['H','h']),n(['Btf','tf']),n(['Bbf','bf']),n(['tw','w']),n(['th1']),n(['bh1']),n(['bh2']),n(['th2'])];return [H,Btf,Bbf,tw,th1,bh1,bh2,th2].every(value=>value!==undefined)?{H:H!,Btf:Btf!,Bbf:Bbf!,tw:tw!,th1:th1!,bh1:bh1!,bh2:bh2!,th2:th2!}:undefined}
const get=canonicalPrecastParameters
function points(g:G,s:number,cx:number,top:number){const sy=(z:number)=>top+z*s,y2=g.th1+g.bh1,y3=g.H-g.bh2-g.th2;return {sy,y2,y3,points:[[-g.Btf/2,0],[-g.Btf/2,g.th1],[-g.tw/2,y2],[-g.tw/2,y3],[-g.Bbf/2,g.H-g.th2],[-g.Bbf/2,g.H],[g.Bbf/2,g.H],[g.Bbf/2,g.H-g.th2],[g.tw/2,y3],[g.tw/2,y2],[g.Btf/2,g.th1],[g.Btf/2,0]].map(([x,y])=>`${cx+x*s},${sy(y)}`).join(' ')}}
function Svg({g,u,small=false}:{g:G;u:ProjectUnits;small?:boolean}){const s=Math.min((small?100:215)/g.H,(small?100:215)/Math.max(g.Btf,g.Bbf)),cx=small?80:170,top=small?18:45,{sy,y2,y3,points:polygon}=points(g,s,cx,top),f=(v:number)=>formatTechnicalDimension(v,(value)=>toDisplayValue(value,'Length',u)),sectionRight=cx+Math.max(g.Btf,g.Bbf)*s/2,rx=sectionRight+P.extensionGap+((340-sectionRight-P.extensionGap)*P.rightDimensionFactor);
 const definitions: ReturnType<typeof resolveHorizontalDimension>[] = [];
 const dimension=(id:keyof G,from:{x:number;y:number},to:{x:number;y:number},side:'left'|'right'|'top'|'bottom'|'inline')=>{const d=side==='top'||side==='bottom'?resolveHorizontalDimension(id,id,from,to,f(g[id])):side==='inline'?resolveInlineDimension(id,id,from,to,f(g[id])):resolveVerticalDimension(id,id,from,to,f(g[id]));const horizontal=side==='top'||side==='bottom'||side==='inline';d.arrows=[{point:d.from,direction:horizontal?'left':'up'},{point:d.to,direction:horizontal?'right':'down'}];const anchorOffset=side==='top'?{x:0,y:15}:side==='bottom'?{x:0,y:-15}:side==='left'?{x:16,y:0}:side==='right'?{x:sectionRight-from.x,y:0}:undefined;if(anchorOffset)d.extensionLines=[dimensionExtensionLine({x:from.x+anchorOffset.x,y:from.y+anchorOffset.y},{x:from.x,y:from.y}),dimensionExtensionLine({x:to.x+anchorOffset.x,y:to.y+anchorOffset.y},{x:to.x,y:to.y})];if(d.text){const gap=P.textGap;if(side==='top')d.text={...d.text,point:{x:d.text.point.x,y:d.text.point.y-gap}};if(side==='bottom')d.text={...d.text,point:{x:d.text.point.x,y:d.text.point.y+gap+P.bbfTextOffsetY}};if(side==='left')d.text={...d.text,point:{x:d.text.point.x-gap,y:d.text.point.y},anchor:'end'};if(side==='right')d.text={...d.text,point:{x:d.text.point.x+gap,y:d.text.point.y},anchor:'start'};if(side==='inline')d.text={...d.text,point:{x:Math.max(from.x,to.x)+gap*P.twTextGapFactor,y:d.text.point.y},anchor:'start'}}definitions.push(d);const renderer=side==='top'||side==='bottom'?<HorizontalDimension definition={d}/>:side==='inline'?<InlineDimension definition={d}/>:<VerticalDimension definition={d}/>;return <g key={id} className="spn-technical-dimension">{renderer}</g>};
 if(small)return <svg className="spn-family-visual-candidate-svg" viewBox="0 0 160 145" role="img" aria-label="Precast girder candidate section"><polygon className="spn-family-precast-section-shape" points={polygon}/></svg>
 const children=<>{dimension('Btf',{x:cx-g.Btf*s/2,y:top-15},{x:cx+g.Btf*s/2,y:top-15},'top')}{dimension('Bbf',{x:cx-g.Bbf*s/2,y:sy(g.H)+15},{x:cx+g.Bbf*s/2,y:sy(g.H)+15},'bottom')}{dimension('H',{x:cx-g.Btf*s/2-16,y:top},{x:cx-g.Btf*s/2-16,y:sy(g.H)},'left')}{dimension('tw',{x:cx-g.tw*s/2,y:sy((y2+y3)/2)},{x:cx+g.tw*s/2,y:sy((y2+y3)/2)},'inline')}{dimension('th1',{x:rx,y:sy(0)},{x:rx,y:sy(g.th1)},'right')}{dimension('bh1',{x:rx,y:sy(g.th1)},{x:rx,y:sy(y2)},'right')}{dimension('bh2',{x:rx,y:sy(y3)},{x:rx,y:sy(g.H-g.th2)},'right')}{dimension('th2',{x:rx,y:sy(g.H-g.th2)},{x:rx,y:sy(g.H)},'right')}</>;
 const bounds=drawingBounds([[cx-g.Btf*s/2,top],[cx+g.Btf*s/2,top],[cx-g.Bbf*s/2,sy(g.H)],[cx+g.Bbf*s/2,sy(g.H)]].map(([x,y])=>({x,y})),definitions,6,11);
 return <svg className="spn-family-precast-preview-svg" viewBox="-45 0 430 350" preserveAspectRatio="xMidYMid meet" data-drawing-bounds={`${bounds.minX},${bounds.minY},${bounds.width},${bounds.height}`} role="img" aria-label="Precast girder technical section"><polygon className="spn-preview-section-fill" points={polygon}/>{children}</svg>}
export default function PrecastGirderFamilyPreview({candidate,projectUnits=readProjectState([]).project.units}:Props){const g=get(candidate);if(!g)return <p>Structural preview is not available for this family type yet.</p>;return <section className="spn-girder-preview" aria-label="Precast Girder Preview"><div className="spn-girder-drawing-viewport" data-testid="girder-preview-viewport"><Svg g={g} u={projectUnits}/></div></section>}
export function PrecastGirderSectionProperties({candidate,projectUnits}: {candidate:FamilyAlternative;projectUnits?:ProjectUnits}){const parameters=canonicalPrecastParameters(candidate),derived=parameters?precastSectionProperties(parameters):undefined,units=projectUnits??readProjectState([]).project.units;const definitions={A:['Cross-sectional Area','Area'],Ix:['Moment of Inertia (X)','Length^4'],Iy:['Moment of Inertia (Y)','Length^4'],Wx:['Section Modulus (X)','Volume'],Wy:['Section Modulus (Y)','Volume']} as const;return <section className="spn-girder-preview-properties" data-testid="section-properties">{(['A','Ix','Iy','Wx','Wy'] as const).map(key=>{const [description,dimension]=definitions[key];const value=derived?.[key];return <p key={key}><span className="property-symbol">{key}</span><span className="property-description">{description}</span><strong className="property-value">{typeof value==='number'&&Number.isFinite(value)&&value>0?formatDisplayValue(value,dimension,units).replace(/\s+(?:m|cm|mm)(?:²|⁴|³)$/, ''):'—'}</strong><span className="property-unit">{units.length ?? 'm'}{key==='A'?'²':key==='Ix'||key==='Iy'?'⁴':'³'}</span></p>})}</section>}
export function PrecastGirderVisualCandidates({candidate,familyCandidates=[],projectUnits=readProjectState([]).project.units,onSelectCandidate}:{candidate:FamilyAlternative;familyCandidates?:readonly FamilyAlternative[];projectUnits?:ProjectUnits;onSelectCandidate?:(id:string)=>void}){const rail=useRef<HTMLDivElement>(null),[canLeft,setCanLeft]=useState(false),[canRight,setCanRight]=useState(false);const update=()=>{const e=rail.current;if(e){setCanLeft(e.scrollLeft>1);setCanRight(e.scrollLeft+e.clientWidth<e.scrollWidth-1)}};useEffect(update,[familyCandidates.length]);useEffect(()=>{rail.current?.querySelector<HTMLElement>(`[data-candidate="${candidate.candidateId}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});update()},[candidate.candidateId]);return <section className="spn-family-visual-candidates" data-testid="visual-candidates"><div className="spn-family-subheading"><h3>Visual Candidates</h3></div><div className="spn-family-visual-navigation"><button type="button" aria-label="Previous candidates" disabled={!canLeft} onClick={()=>rail.current?.scrollBy({left:-rail.current.clientWidth*.75,behavior:'smooth'})}>‹</button><div ref={rail} onScroll={update} className="spn-family-visual-candidate-strip">{familyCandidates.map((item,index)=>{const g=get(item);return g?<button type="button" key={item.candidateId} data-candidate={item.candidateId} className={item.candidateId===candidate.candidateId?'selected':''} aria-selected={item.candidateId===candidate.candidateId} onClick={()=>onSelectCandidate?.(item.candidateId)}><Svg g={g} u={projectUnits} small/><span>PG-{String(index+1).padStart(3,'0')}</span><small>H = {g.H.toFixed(2)} m<br/>Bbf = {g.Bbf.toFixed(2)} m</small></button>:null})}</div><button type="button" aria-label="Next candidates" disabled={!canRight} onClick={()=>rail.current?.scrollBy({left:rail.current.clientWidth*.75,behavior:'smooth'})}>›</button></div></section>}
