import { useState } from 'react'
import type { FamilyAlternative } from '../../graph/family/familyResults'
import { toDisplayValue, type ProjectUnits } from '../../graph/domain/quantities'
import { readProjectState } from '../../project/model/projectWorkspace'

type Props={candidate:FamilyAlternative;familyCandidates?:readonly FamilyAlternative[];projectUnits?:ProjectUnits;displayId?:string;onSelectCandidate?:(id:string)=>void;showDetails?:boolean}
type Girder={H:number;Btf:number;Bbf:number;tw:number;th1:number;bh1:number;th2:number;bh2:number}
const get=(c:FamilyAlternative):Girder|undefined=>{const g=(((c.candidateData as Record<string,unknown>).geometry??{}) as Record<string,unknown>),n=(ks:string[])=>ks.map(k=>g[k]).find((v):v is number=>typeof v==='number'&&Number.isFinite(v)),[H,Btf,Bbf,tw,th1,bh1,th2,bh2]=[n(['H']),n(['Btf','tf']),n(['Bbf','bf']),n(['tw','w']),n(['th1']),n(['bh1']),n(['th2']),n(['bh2'])];return[H,Btf,Bbf,tw,th1,bh1,th2,bh2].some(v=>v===undefined)?undefined:{H:H!,Btf:Btf!,Bbf:Bbf!,tw:tw!,th1:th1!,bh1:bh1!,th2:th2!,bh2:bh2!}}
function geom(g:Girder,s:number,cx:number,top:number){const sy=(z:number)=>top+z*s,sx=(z:number)=>cx+z*s,y2=g.th1+g.bh1,y3=g.H-g.bh2-g.th2;return{sy,y2,y3,points:[[-g.Btf/2,0],[-g.Btf/2,g.th1],[-g.tw/2,y2],[-g.tw/2,y3],[-g.Bbf/2,g.H-g.th2],[-g.Bbf/2,g.H],[g.Bbf/2,g.H],[g.Bbf/2,g.H-g.th2],[g.tw/2,y3],[g.tw/2,y2],[g.Btf/2,g.th1],[g.Btf/2,0]].map(([x,y])=>`${sx(x)},${sy(y)}`).join(' ')}}
function Svg({g,u,small=false,three=false,envelope}:{g:Girder;u:ProjectUnits;small?:boolean;three?:boolean;envelope?:{h:number;w:number}}){const s=Math.min((small?100:217.5)*1.2/(envelope?.h??g.H),(small?100:217.5)*1.2/(envelope?.w??Math.max(g.Btf,g.Bbf))),cx=small?80:170,top=small?18:58,{sy,y2,y3,points}=geom(g,s,cx,top),f=(v:number)=>toDisplayValue(v,'Length',u).toFixed(2),shapeStyle={fill:three?'#68737d':'#aeb3b5',stroke:'#d9dde0',strokeWidth:1.5,opacity:1};return <svg className={small?'spn-family-visual-candidate-svg':'spn-family-precast-preview-svg'} viewBox={small?'0 0 160 145':'0 0 340 350'} preserveAspectRatio="xMidYMid meet"><polygon className={three?'spn-preview-section-shadow':'spn-family-precast-section-shape'} style={shapeStyle} points={points}/><polygon className="spn-family-precast-section-shape" style={shapeStyle} points={points}/>{!small&&!three&&<><text className="spn-family-section-dimension" x={cx} y={top-8} textAnchor="middle">Btf = {f(g.Btf)}</text><text className="spn-family-section-dimension" x={cx} y={sy(g.H)+18} textAnchor="middle">Bbf = {f(g.Bbf)}</text><text className="spn-family-section-dimension" x="45" y={sy(g.H/2)} textAnchor="middle">H = {f(g.H)}</text><text className="spn-family-section-dimension" x={cx+g.tw*s/2+16} y={sy((y2+y3)/2)}>tw = {f(g.tw)}</text><text className="spn-family-section-dimension" x="292" y={sy(g.th1/2)}>th1 = {f(g.th1)}</text><text className="spn-family-section-dimension" x="292" y={sy(g.th1+g.bh1/2)}>bh1 = {f(g.bh1)}</text><text className="spn-family-section-dimension" x="292" y={sy(g.H-g.th2/2)}>th2 = {f(g.th2)}</text><text className="spn-family-section-dimension" x="292" y={sy(g.H-g.th2-g.bh2/2)}>bh2 = {f(g.bh2)}</text></>}</svg>}
function props(g:Girder){const p=[[-g.Btf/2,0],[-g.Btf/2,g.th1],[-g.tw/2,g.th1+g.bh1],[-g.tw/2,g.H-g.bh2-g.th2],[-g.Bbf/2,g.H-g.th2],[-g.Bbf/2,g.H],[g.Bbf/2,g.H],[g.Bbf/2,g.H-g.th2],[g.tw/2,g.H-g.bh2-g.th2],[g.tw/2,g.th1+g.bh1],[g.Btf/2,g.th1],[g.Btf/2,0]];let a=0,sx=0,sy=0,ix=0,iy=0;p.forEach((q,i)=>{const r=p[(i+1)%p.length],c=q[0]*r[1]-r[0]*q[1];a+=c;sx+=(q[0]+r[0])*c;sy+=(q[1]+r[1])*c;ix+=(q[1]**2+q[1]*r[1]+r[1]**2)*c;iy+=(q[0]**2+q[0]*r[0]+r[0]**2)*c});a/=2;return{a:Math.abs(a),ix:Math.abs(ix/12-a*(sy/(6*a))**2),iy:Math.abs(iy/12-a*(sx/(6*a))**2)}}
function Properties({g,u}:{g:Girder;u:ProjectUnits}){const p=props(g),digits=u.length==='m'?4:u.length==='cm'?2:0,unit=u.length??'m',f=(v:number,suffix:string)=>`${v.toFixed(digits)} ${unit}${suffix}`;return <div className="spn-girder-preview-properties" data-testid="section-properties"><h4>SECTION PROPERTIES</h4><p><span>A =</span><strong>{f(p.a,'²')}</strong></p><p><span>Ix =</span><strong>{f(p.ix,'⁴')}</strong></p><p><span>Iy =</span><strong>{f(p.iy,'⁴')}</strong></p></div>}
function Visual({items,selected,onSelect,u}:{items:readonly FamilyAlternative[];selected:string;onSelect?:(id:string)=>void;u:ProjectUnits}){const gs=items.map(get).filter((v):v is Girder=>Boolean(v)),envelope={h:Math.max(...gs.map(g=>g.H),1),w:Math.max(...gs.map(g=>Math.max(g.Btf,g.Bbf)),1)};return <section className="spn-family-visual-candidates"><div className="spn-family-subheading"><h3>Visual Candidates</h3><span>{items.length} alternatives</span></div><div className="spn-family-visual-candidate-strip">{items.map((c,i)=>{const g=get(c);return g?<button type="button" key={c.candidateId} className={c.candidateId===selected?'selected':''} onClick={()=>onSelect?.(c.candidateId)}><Svg g={g} u={u} small envelope={envelope}/><span>{`PG-${String(i+1).padStart(3,'0')}`}</span><small>H = {g.H.toFixed(2)} m<br/>Bbf = {g.Bbf.toFixed(2)} m</small></button>:null})}</div></section>}
export function PrecastGirderSectionProperties({candidate,projectUnits}:Pick<Props,'candidate'|'projectUnits'>){const g=get(candidate);return g?<Properties g={g} u={projectUnits??readProjectState([]).project.units}/>:null}
export function PrecastGirderVisualCandidates({candidate,familyCandidates,projectUnits,onSelectCandidate}:Pick<Props,'candidate'|'familyCandidates'|'projectUnits'|'onSelectCandidate'>){return <Visual items={familyCandidates??[candidate]} selected={candidate.candidateId} onSelect={onSelectCandidate} u={projectUnits??readProjectState([]).project.units}/>}
export default function PrecastGirderFamilyPreview({candidate,familyCandidates=[candidate],projectUnits=readProjectState([]).project.units,displayId,onSelectCandidate,showDetails=true}:Props){const g=get(candidate),[mode,setMode]=useState<'2d'|'3d'>('2d');if(!g)return <p>Structural preview is not available for this family type yet.</p>;const all=familyCandidates.map(get).filter((v):v is Girder=>Boolean(v)),envelope={h:Math.max(...all.map(v=>v.H),g.H),w:Math.max(...all.map(v=>Math.max(v.Btf,v.Bbf)),g.Btf,g.Bbf)};return <section className="spn-girder-preview" aria-label="Precast Girder Preview"><div className="spn-girder-preview-heading"><h3>SECTION PREVIEW ({displayId??'PG-001'})</h3><div className="spn-preview-tabs"><button type="button" className={mode==='2d'?'active':''} onClick={()=>setMode('2d')}>2D Section</button><button type="button" className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}>3D View</button></div></div><div className="spn-girder-drawing-viewport" data-testid="girder-preview-viewport"><Svg g={g} u={projectUnits} envelope={envelope} three={mode==='3d'}/></div>{showDetails&&<><Properties g={g} u={projectUnits}/><Visual items={familyCandidates} selected={candidate.candidateId} onSelect={onSelectCandidate} u={projectUnits}/></>}</section>}
