import { useEffect, useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from 'react'
import { generateValues, type Dimension } from '../../../shared/ui/ParamSweepCard'
import { defaultDimensions, generatePierVariants, statusOfPierFamily } from '../model/service'
import { DesignSystemSection, EngineeringInput, GenerationTable } from '../../../shared/ui/DesignSystemUi'
import type { PierConfiguration, PierFamily, PierType } from '../model/types'
import { getFamilyReferences, publishFamilySelection } from '../../family-registry/model/registry'
import { useFamilyCatalog } from '../../family-registry/hooks/useFamilyCatalog'

const STORAGE_KEY = 'spanova.project-design-system.pier-families'
const emptyHeight = { minimumHeight: null, preferredHeightMin: null, preferredHeightMax: null, maximumHeight: null }
const INITIAL: PierFamily[] = [{ id: 'RECT-M', name: 'RECT-M', pierType: 'RECTANGULAR', enabled: false, dimensions: defaultDimensions('RECTANGULAR'), allowedConfigurations: ['SINGLE_COLUMN', 'TWO_COLUMNS'], twoColumnSpacing: { key: 'spacing', label: 'Transverse Spacing (m)', min: 6, max: 10, delta: 1 }, heightApplicability: emptyHeight, source: 'PROJECT_DESIGN_SYSTEM' }]

function readFamilies() {
  if (typeof window === 'undefined') return INITIAL
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? 'null') as PierFamily[] | null
    return saved?.map((family) => ({ ...family, pierType: family.pierType === ('H_TYPE' as PierType) || family.pierType === ('WALL' as PierType) ? 'H_SECTION' : family.pierType, allowedConfigurations: family.allowedConfigurations.filter((value) => value === 'SINGLE_COLUMN' || value === 'TWO_COLUMNS') })) ?? INITIAL
  } catch { return INITIAL }
}

export default function PierFamiliesPanel() {
  const [families, setFamilies] = useFamilyCatalog<PierFamily>('PIER', readFamilies)
  const [selectedId, setSelectedId] = useState(families[0]?.id ?? '')
  const family = families.find((item) => item.id === selectedId) ?? families[0]
  const variants = useMemo(() => family ? generatePierVariants(family) : [], [family])
  useEffect(() => { publishFamilySelection('PIER', selectedId || null) }, [selectedId])
  const [deleteError, setDeleteError] = useState('')
  if (!family) return <div className="spn-card"><h2 className="spn-card-title">PIER</h2><p className="spn-card-subtitle">Project Design System / User Defined</p><button className="spn-button-primary" onClick={() => addFamily(createFamily('RECTANGULAR'), setFamilies, setSelectedId)}>Add Pier</button></div>

  const update = (patch: Partial<PierFamily>) => setFamilies((items) => items.map((item) => item.id === family.id ? { ...item, ...patch } : item))
  const updateDimension = (key: string, patch: Partial<Dimension>) => update({ dimensions: family.dimensions.map((dimension) => dimension.key === key ? { ...dimension, ...patch } : dimension) })
  const status = statusOfPierFamily(family)
  const deleteFamily = (id: string) => {
    const references = getFamilyReferences('PIER', id)
    if (references.length) { setDeleteError(`Cannot delete ${id}; used by ${references.map((item) => `${item.bridgeId} / ${item.location}`).join(', ')}.`); return }
    const next = families.filter((item) => item.id !== id)
    setFamilies(next); setSelectedId(next[0]?.id ?? '') ; setDeleteError('')
  }

  return <div className="spn-workflow">
    <div className="spn-card">
      <div className="spn-shape-card-header"><div><h2 className="spn-card-title">PIER</h2><p className="spn-card-subtitle">Project Design System / User Defined</p></div><label className="spn-checklist-item"><input type="checkbox" checked={family.enabled} onChange={(event) => update({ enabled: event.target.checked })} /> Use in SPANOVA analyses</label></div>
      <div className="spn-field-grid" style={{ gridTemplateColumns: '1fr 1fr' }}><label className="spn-field">Family Name<input className="spn-input" value={family.name} onChange={(event) => update({ name: event.target.value })} /></label><label className="spn-field">Pier Type<select className="spn-input" value={family.pierType} onChange={(event) => { const pierType = event.target.value as PierType; update({ pierType, dimensions: defaultDimensions(pierType) }) }}><option value="RECTANGULAR">Rectangular</option><option value="CIRCULAR">Circular</option><option value="OVAL">Oval</option><option value="BOX">Box</option><option value="H_SECTION">H section</option></select></label></div>
      <PierShapeDiagram type={family.pierType} />
      <DesignSystemSection title="SECTION GENERATION">{family.dimensions.length ? <GenerationTable dimensions={family.dimensions} onUpdateDimension={updateDimension} /> : <p className="spn-hint">Not configured yet for this pier type.</p>}</DesignSystemSection>
      <Section title="CONFIGURATION"><div style={{ display: 'flex', gap: 18, flexWrap: 'wrap' }}>{([['SINGLE_COLUMN', 'Single Column'], ['TWO_COLUMNS', 'Two Columns']] as [PierConfiguration, string][]).map(([value, label]) => <label className="spn-checklist-item" key={value}><input type="checkbox" checked={family.allowedConfigurations.includes(value)} onChange={(event) => update({ allowedConfigurations: event.target.checked ? [...family.allowedConfigurations, value] : family.allowedConfigurations.filter((item) => item !== value) })} /> {label}</label>)}</div>{family.allowedConfigurations.includes('TWO_COLUMNS') && <SpacingSection family={family} update={update} />}</Section>
      <Section title="HEIGHT APPLICABILITY"><div className="pier-height-applicability-grid">{([['minimumHeight', 'Minimum Height'], ['preferredHeightMin', 'Preferred Height Min'], ['preferredHeightMax', 'Preferred Height Max'], ['maximumHeight', 'Maximum Height']] as const).map(([key, label]) => <div className="pier-height-field" key={key}><label>{label}</label><div className="pier-height-input-row"><NumberInput value={family.heightApplicability[key] ?? ''} onChange={(value) => update({ heightApplicability: { ...family.heightApplicability, [key]: value } })} /><span>m</span></div></div>)}</div><HeightRangeVisualization family={family} /><p className="spn-hint">Actual pier height is supplied later from project geometry; no height candidates or rounding are generated here.</p></Section>
      <p>Generated Section Variants: <strong>{variants.length}</strong></p><p>Status: <strong>{status}</strong></p><div style={{ display: 'flex', gap: 8 }}><button className="spn-button-primary" disabled={status !== 'VALID'} onClick={() => addFamily(family, setFamilies, setSelectedId)}>Add Pier</button></div>
    </div>
    <div className="spn-card"><h3 className="spn-card-title">PIER FAMILY CATALOG</h3><table className="spn-table"><thead><tr><th>Family</th><th>Type</th><th>Section Variants</th><th>Configurations</th><th>Height Range</th><th>Preferred Range</th><th>Enabled</th><th>Status</th><th>Delete</th></tr></thead><tbody>{families.map((item) => <tr key={item.id} onClick={() => { setSelectedId(item.id); publishFamilySelection('PIER', item.id) }} className={item.id === selectedId ? 'spn-row-selected' : ''} style={{ cursor: 'pointer' }}><td>{item.name}</td><td>{item.pierType}</td><td>{generatePierVariants(item).length}</td><td>{item.allowedConfigurations.join(', ') || '-'}</td><td>{item.heightApplicability.minimumHeight ?? '-'} - {item.heightApplicability.maximumHeight ?? '-'} m</td><td>{item.heightApplicability.preferredHeightMin ?? '-'} - {item.heightApplicability.preferredHeightMax ?? '-'} m</td><td>{item.enabled ? 'Yes' : 'No'}</td><td>{statusOfPierFamily(item)}</td><td><button className="spn-button-secondary" onClick={(event) => { event.stopPropagation(); deleteFamily(item.id) }}>Delete</button></td></tr>)}</tbody></table>{deleteError && <p role="alert" className="spn-validation-error">{deleteError}</p>}</div>
  </div>
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <DesignSystemSection title={title}>{children}</DesignSystemSection> }
function NumberInput({ value, onChange }: { value: number | string; onChange: (value: number) => void }) { return <EngineeringInput value={value} onChange={onChange} /> }
function validValues(dimension: Dimension) { return dimension.min > 0 && dimension.max >= dimension.min && dimension.delta > 0 ? generateValues(dimension.min, dimension.max, dimension.delta).map((value) => Number(value.toFixed(10))) : [] }
function createFamily(type: PierType): PierFamily { return { id: `PIER-${Date.now()}`, name: 'New Pier Family', pierType: type, enabled: false, dimensions: defaultDimensions(type), allowedConfigurations: ['SINGLE_COLUMN'], twoColumnSpacing: null, heightApplicability: emptyHeight, source: 'PROJECT_DESIGN_SYSTEM' } }
function PierShapeDiagram({ type }: { type: PierType }) { return <div className="spn-shape-card-diagram"><svg viewBox="0 0 220 155" width="220" height="155" role="img" aria-label={`${type} pier section`}><line x1="20" y1="130" x2="200" y2="130" stroke="var(--accent)" strokeWidth="2" /><text x="110" y="145" textAnchor="middle" fill="var(--text-secondary)" fontSize="10">Bridge Axis</text>{type === 'CIRCULAR' && <circle cx="110" cy="60" r="38" fill="var(--accent)" fillOpacity=".2" stroke="var(--accent)" strokeWidth="2" />}{type === 'OVAL' && <rect transform="rotate(90 110 60)" x="55" y="35" width="110" height="50" rx="25" fill="var(--accent)" fillOpacity=".2" stroke="var(--accent)" strokeWidth="2" />}{type === 'BOX' && <path transform="rotate(90 110 60)" d="M55 28 H165 V92 H55 Z M70 43 H150 V77 H70 Z" fill="var(--accent)" fillOpacity=".2" fillRule="evenodd" stroke="var(--accent)" strokeWidth="2" />}{type === 'H_SECTION' && <path transform="rotate(90 110 60)" d="M70 28 H150 V45 H122 V85 H150 V102 H70 V85 H98 V45 H70 Z" fill="var(--accent)" fillOpacity=".2" stroke="var(--accent)" strokeWidth="2" />}{type === 'RECTANGULAR' && <rect x="70" y="25" width="80" height="70" fill="var(--accent)" fillOpacity=".2" stroke="var(--accent)" strokeWidth="2" />}</svg></div> }
function SpacingSection({ family, update }: { family: PierFamily; update: (patch: Partial<PierFamily>) => void }) { const spacing = family.twoColumnSpacing; if (!spacing) return <p className="spn-hint">Not configured yet.</p>; const values = validValues(spacing); return <div style={{ marginTop: 14, display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'end' }}><p className="spn-field-label" style={{ width: '100%' }}>Two-Column Spacing</p>{(['min', 'max', 'delta'] as const).map((key) => <label className="spn-field" key={key}>{key[0].toUpperCase() + key.slice(1)}<div style={{ display: 'flex', alignItems: 'center', gap: 4 }}><NumberInput value={spacing[key]} onChange={(value) => update({ twoColumnSpacing: { ...spacing, [key]: value } })} /><span>m</span></div></label>)}<div><div className="spn-field-label">Values SPANOVA Will Use</div><div>{values.length ? `${values.join(', ')} m` : 'Not configured yet'}</div></div></div> }
function HeightRangeVisualization({ family }: { family: PierFamily }) { const h = family.heightApplicability; if ([h.minimumHeight, h.preferredHeightMin, h.preferredHeightMax, h.maximumHeight].some((value) => value == null || !Number.isFinite(value))) return null; const range = h.maximumHeight! - h.minimumHeight! || 1; const position = (value: number) => `${((value - h.minimumHeight!) / range) * 100}%`; return <div style={{ marginTop: 18 }}><div style={{ position: 'relative', height: 48, margin: '0 8px' }}><div style={{ position: 'absolute', top: 18, left: 0, right: 0, borderTop: '2px solid var(--border)' }} /><div style={{ position: 'absolute', top: 13, left: position(h.preferredHeightMin!), width: `${((h.preferredHeightMax! - h.preferredHeightMin!) / range) * 100}%`, borderTop: '6px solid var(--accent)' }} />{[h.minimumHeight!, h.preferredHeightMin!, h.preferredHeightMax!, h.maximumHeight!].map((value, index) => <span key={`${value}-${index}`} style={{ position: 'absolute', left: position(value), top: 8, transform: 'translateX(-50%)' }}>|</span>)}<span style={{ position: 'absolute', left: 0, top: 28 }}>{h.minimumHeight} m</span><span style={{ position: 'absolute', left: position(h.preferredHeightMin!), top: 28, transform: 'translateX(-50%)' }}>{h.preferredHeightMin} m</span><span style={{ position: 'absolute', left: position(h.preferredHeightMax!), top: 28, transform: 'translateX(-50%)' }}>{h.preferredHeightMax} m</span><span style={{ position: 'absolute', right: 0, top: 28 }}>{h.maximumHeight} m</span></div><small>APPLICABLE &nbsp;&nbsp;&nbsp;&nbsp; PREFERRED &nbsp;&nbsp;&nbsp;&nbsp; APPLICABLE</small></div> }
function addFamily(source: PierFamily, setFamilies: Dispatch<SetStateAction<PierFamily[]>>, setSelectedId: (id: string) => void) { const id = `PIER-${Date.now()}`; setFamilies((items) => [...items, { ...source, id, name: `${source.name}-COPY`, dimensions: source.dimensions.map((dimension) => ({ ...dimension })), allowedConfigurations: [...source.allowedConfigurations], twoColumnSpacing: source.twoColumnSpacing ? { ...source.twoColumnSpacing } : null, heightApplicability: { ...source.heightApplicability } }]); setSelectedId(id) }
