import type { GraphParameterValue, GraphPortType, GraphValue, MaterialValue, SpanovaNode } from '../domain/types'
import { makeQuantity, QUANTITY_KINDS as UNIT_KINDS, type QuantityKind, type UnitId, unitsForKind } from '../domain/quantities'
import { EN_CONCRETE_CLASS_IDS } from '../../materials/model/materialCatalog'

export type NodeCategory = 'INPUT' | 'MATH' | 'MATERIALS' | 'OUTPUT'
export type ParameterDescriptor = { key: string; label: string; dataType: 'number' | 'integer' | 'boolean' | 'string' | 'select'; min?: number; step?: number; options?: readonly { value: string; label: string }[] }
export type NodePortDefinition = { id: string; label: string; type: GraphPortType; quantityKind?: QuantityKind; domainType?: MaterialValue['domainType']; required?: boolean }
export interface GraphExecutionServices { resolveConcreteMaterial?: (materialId:string)=>Promise<MaterialValue> }
export type NodeExecutionContext = { node: SpanovaNode; inputs: Record<string, GraphValue>; services?: GraphExecutionServices }
export interface NodeDefinition { type: string; label: string; category: NodeCategory; description: string; inputs: NodePortDefinition[]; outputs: NodePortDefinition[]; parameterSchema: ParameterDescriptor[]; createDefaultParameters: (projectUnits?: Record<string,string>) => Record<string,GraphParameterValue>; validateParameters: (parameters: Record<string,GraphParameterValue>) => string[]; executor: (context:NodeExecutionContext)=>Record<string,GraphValue>|Promise<Record<string,GraphValue>> }
const noParameters=(p:Record<string,GraphParameterValue>)=>Object.keys(p).length?['This node does not accept parameters.']:[]
function numberParameter(p:Record<string,GraphParameterValue>,key:string,integer=false):string[]{const v=p[key];return typeof v!=='number'||!Number.isFinite(v)||(integer&&!Number.isInteger(v))?[`${key} must be a valid ${integer?'integer':'number'}.`]:[]}
function scalarDefinition(type:string,label:string,dataType:'number'|'integer'|'boolean'):NodeDefinition{return{type,label,category:'INPUT',description:`Provide a ${dataType} value.`,inputs:[],outputs:[{id:'value',label:'Value',type:dataType}],parameterSchema:[{key:'value',label:'Value',dataType,step:dataType==='integer'?1:.01}],createDefaultParameters:()=>({value:dataType==='boolean'?false:0}),validateParameters:p=>dataType==='boolean'?(typeof p.value==='boolean'?[]:['Value must be boolean.']):numberParameter(p,'value',dataType==='integer'),executor:({node})=>({value:node.parameters.value as GraphValue})}}
function math(type:string,label:string,operation:'add'|'subtract'|'multiply'|'divide'):NodeDefinition{return{type,label,category:'MATH',description:`${label} dimensionless numbers or compatible quantities.`,inputs:[{id:'a',label:'A',type:'numeric',required:true},{id:'b',label:'B',type:'numeric',required:true}],outputs:[{id:'result',label:'Result',type:'numeric'}],parameterSchema:[],createDefaultParameters:()=>({}),validateParameters:noParameters,executor:({inputs})=>{const a=inputs.a,b=inputs.b;if(typeof a==='object'&&a!==null&&!Array.isArray(a)||typeof b==='object'&&b!==null&&!Array.isArray(b)){const qa=typeof a==='object'&&a!==null&&!Array.isArray(a)?a as import('../domain/quantities').EngineeringQuantity:undefined,qb=typeof b==='object'&&b!==null&&!Array.isArray(b)?b as import('../domain/quantities').EngineeringQuantity:undefined;const na=typeof a==='number',nb=typeof b==='number';let kind:QuantityKind,value:number;if(operation==='add'||operation==='subtract'){if(!qa||!qb||qa.quantityKind!==qb.quantityKind)throw new Error('Addition and subtraction require quantities of the same kind.');kind=qa.quantityKind;value=operation==='add'?qa.value+qb.value:qa.value-qb.value}else if(operation==='multiply'){if(qa&&qb)throw new Error('Multiplying two quantities is not supported yet.');if(!qa&&!qb)throw new Error('Expected numeric inputs.');kind=(qa??qb)!.quantityKind;value=(qa??qb)!.value*(na?a as number:b as number)}else{if(!qa)throw new Error('The numerator must be a quantity when using quantity division.');if(!nb)throw new Error('A quantity may only be divided by a dimensionless number.');if(b===0)throw new Error('Division by zero.');kind=qa.quantityKind;value=qa.value/b}return{result:{value,quantityKind:kind,unit:(qa??qb)!.unit}}}const x=Number(a),y=Number(b);let result=operation==='add'?x+y:operation==='subtract'?x-y:operation==='multiply'?x*y:y===0?(()=>{throw new Error('Division by zero.')})():x/y;if(!Number.isFinite(result))throw new Error('Operation produced a non-finite number.');return{result}}}}
const classOptions=EN_CONCRETE_CLASS_IDS.map(value=>({value,label:value}))
function materialNode(type:string,label:string,domainType:MaterialValue['domainType'],options:readonly {value:string;label:string}[]=[]):NodeDefinition{return{type,label,category:'MATERIALS',description:`Create a typed ${label} material reference from configured project data.`,inputs:[],outputs:[{id:'material',label, type:domainType==='ConcreteMaterial'?'concreteMaterial':domainType==='ReinforcementMaterial'?'reinforcementMaterial':domainType==='PrestressingSteelMaterial'?'prestressingSteelMaterial':'structuralSteelMaterial',domainType}],parameterSchema:[{key:'materialId',label:'Material',dataType:'select',options}],createDefaultParameters:()=>({materialId:options[0]?.value??''}),validateParameters:p=>typeof p.materialId!=='string'||!options.some(o=>o.value===p.materialId)?[options.length?'Select a supported material.':`${label} catalog data are not configured in SPANOVA.`]:[],executor:async({node,services})=>{const id=node.parameters.materialId as string;if(!options.some(o=>o.value===id))throw new Error(`Unknown ${label} material ID: ${id}.`);if(domainType==='ConcreteMaterial'&&services?.resolveConcreteMaterial)return{material:await services.resolveConcreteMaterial(id)};return{material:{domainType,id,name:id,properties:{}}}}}}
const definitions:NodeDefinition[]=[
 scalarDefinition('input.number','Number','number'),scalarDefinition('input.integer','Integer','integer'),scalarDefinition('input.boolean','Boolean','boolean'),
 {type:'input.quantity',label:'Quantity',category:'INPUT',description:'Provide a unit-aware engineering quantity.',inputs:[],outputs:[{id:'value',label:'Value',type:'quantity'}],parameterSchema:[{key:'value',label:'Value',dataType:'number',step:.01},{key:'quantityKind',label:'Quantity Kind',dataType:'select',options:[{value:'length',label:'Length'},{value:'area',label:'Area'},{value:'volume',label:'Volume'},{value:'angle',label:'Angle'},{value:'force',label:'Force'},{value:'moment',label:'Moment'},{value:'stress',label:'Stress'},{value:'mass',label:'Mass'},{value:'density',label:'Density'},{value:'unitWeight',label:'Unit Weight'},{value:'temperature',label:'Temperature'},{value:'temperatureDifference',label:'Temperature Difference'},{value:'acceleration',label:'Acceleration'},{value:'translationalStiffness',label:'Translational Stiffness'},{value:'rotationalStiffness',label:'Rotational Stiffness'},{value:'dimensionless',label:'Dimensionless'}]},
  {key:'unit',label:'Unit',dataType:'select',options:[] }],createDefaultParameters:(prefs)=>{const kind='length';return{value:1,quantityKind:kind,unit:defaultUnit(kind,prefs)}},validateParameters:p=>quantityErrors(p,false),executor:({node})=>({value:makeQuantity(node.parameters.value as number,node.parameters.quantityKind as QuantityKind,node.parameters.unit as UnitId)})},
 {type:'input.range',label:'Range',category:'INPUT',description:'Generate inclusive, stepped numeric or quantity values.',inputs:[],outputs:[{id:'values',label:'Values',type:'numeric[]'}],parameterSchema:[{key:'min',label:'Min',dataType:'number',step:.01},{key:'max',label:'Max',dataType:'number',step:.01},{key:'step',label:'Step',dataType:'number',min:1e-10,step:.01},{key:'quantityKind',label:'Quantity Kind',dataType:'select',options:[{value:'dimensionless',label:'Dimensionless'},{value:'length',label:'Length'},{value:'area',label:'Area'},{value:'volume',label:'Volume'},{value:'angle',label:'Angle'},{value:'force',label:'Force'},{value:'moment',label:'Moment'},{value:'stress',label:'Stress'},{value:'mass',label:'Mass'},{value:'density',label:'Density'},{value:'unitWeight',label:'Unit Weight'},{value:'temperature',label:'Temperature'},{value:'temperatureDifference',label:'Temperature Difference'},{value:'acceleration',label:'Acceleration'},{value:'translationalStiffness',label:'Translational Stiffness'},{value:'rotationalStiffness',label:'Rotational Stiffness'}]},{key:'unit',label:'Unit',dataType:'select',options:[]}],createDefaultParameters:prefs=>({min:0,max:10,step:1,quantityKind:'dimensionless',unit:defaultUnit('dimensionless',prefs)}),validateParameters:p=>[...numberParameter(p,'min'),...numberParameter(p,'max'),...numberParameter(p,'step'),...(typeof p.step==='number'&&p.step<=0?['Step must be greater than zero.']:[]),...(typeof p.min==='number'&&typeof p.max==='number'&&p.max<p.min?['Max must be greater than or equal to Min.']:[]),...quantityErrors(p,true),...(typeof p.min==='number'&&typeof p.max==='number'&&typeof p.step==='number'&&Math.floor((p.max-p.min)/p.step+1e-10)>9999?['Range exceeds the 10,000 value execution limit.']:[])],executor:({node})=>{const p=node.parameters as {min:number;max:number;step:number;quantityKind?:QuantityKind;unit?:UnitId};const kind=p.quantityKind??'dimensionless';const unit=p.unit??'1';const count=Math.floor((p.max-p.min)/p.step+1e-10);const vals=Array.from({length:count+1},(_,i)=>Number((p.min+i*p.step).toFixed(10)));return{values:kind==='dimensionless'?vals:vals.map(v=>makeQuantity(v,kind,unit))}}},
 math('math.add','Add','add'),math('math.subtract','Subtract','subtract'),math('math.multiply','Multiply','multiply'),math('math.divide','Divide','divide'),
 materialNode('material.concrete','Concrete','ConcreteMaterial',classOptions),materialNode('material.reinforcement','Reinforcement Steel','ReinforcementMaterial'),materialNode('material.prestressing','Prestressing Steel','PrestressingSteelMaterial'),materialNode('material.structuralSteel','Structural Steel','StructuralSteelMaterial'),
 {type:'output.watch',label:'Watch',category:'OUTPUT',description:'Display supported primitive, quantity and material values.',inputs:[{id:'value',label:'Value',type:'display:any',required:true}],outputs:[],parameterSchema:[],createDefaultParameters:()=>({}),validateParameters:noParameters,executor:({inputs})=>({value:inputs.value})},
]
function quantityErrors(p:Record<string,GraphParameterValue>,range:boolean):string[]{const kind=(p.quantityKind??'dimensionless') as QuantityKind;const unit=(p.unit??'1') as string;const u=getValidUnit(unit,kind);const errors:string[]=[];if(!UNIT_KINDS.includes(kind))errors.push('Select a valid quantity kind.');if(!u)errors.push(`Unit ${String(p.unit)} is invalid for ${String(kind)}.`);if(!range)errors.push(...numberParameter(p,'value'));return errors}
function getValidUnit(unit:string,kind:QuantityKind){return unitsForKind(kind).some(u=>u.id===unit)}
function defaultUnit(kind:string,prefs?:Record<string,string>){const prefKey:Record<string,string>={length:'length',force:'force',moment:'moment',stress:'stress',mass:'mass',temperature:'temperature'};const pref=prefs?.[prefKey[kind]??''];const match=unitsForKind(kind as QuantityKind).find(u=>u.label===pref||u.id===pref);return match?.id??unitsForKind(kind as QuantityKind)[0]?.id??'1'}
export const NODE_REGISTRY:readonly NodeDefinition[]=definitions
const byType=new Map(definitions.map(d=>[d.type,d]))
export function getNodeDefinition(type:string){return byType.get(type)}
export function getNodeDefinitions(category?:NodeCategory){return category?definitions.filter(d=>d.category===category):definitions}
export function canConnect(source:GraphPortType,target:GraphPortType,sourceKind?:QuantityKind,targetKind?:QuantityKind){if(target==='display:any')return ['number','integer','boolean','string','number[]','integer[]','numeric[]','quantity','quantity[]','concreteMaterial','reinforcementMaterial','prestressingSteelMaterial','structuralSteelMaterial','numeric'].includes(source);if(target==='numeric')return ['number','integer','quantity','numeric'].includes(source);if(source==='quantity'&&target==='quantity'&&sourceKind&&targetKind)return sourceKind===targetKind;return source===target||(source==='integer'&&target==='number')}
