import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import EngineeringWorkspace from '../../../shared/ui/EngineeringWorkspace'
import { ABUTMENT_ASSEMBLY, PIER_ASSEMBLY, type VerticalSystemDefinition } from '../model/types'
import { generatePrecastGirderVariants, PRECAST_DIMENSIONS } from '../../girder-library/model/variants'
import type { PreferredSpanRule } from '../../preferred-span/model/types'
import { generatePierVariants } from '../../pier-families/model/service'
import type { PierFamily } from '../../pier-families/model/types'
import { generatePierCapVariants, structuralSystem } from '../../pier-cap-families/model/service'
import type { PierCapFamily } from '../../pier-cap-families/model/types'
import { generateBearingVariants, statusOf as bearingStatus, displayValue } from '../../bearing-families/model/service'
import type { BearingFamily } from '../../bearing-families/model/types'

function Assembly({ definition, selectedId, onSelect }: { definition: VerticalSystemDefinition; selectedId: string | null; onSelect: (id: string) => void }) {
  const hit = (id: string, _route?: string) => onSelect(id)
  const node = (id: string) => definition.nodes.find((item) => item.id === id)!
  const selected = (id: string) => selectedId === id ? ' spn-svg-selected' : ''
  const Box = ({ id, x, y, w, h, label, route: _route }: { id: string; x: number; y: number; w: number; h: number; label?: string; route?: string }) => <g className={`spn-svg-element spn-svg-${id}${selected(id)}`} onClick={() => hit(id)}>{id === 'girder' ? <rect x={x} y={y} width={w} height={h} /> : id === 'bearing' ? <><rect x={x} y={y} width={w} height={h} /><line x1={x + 8} y1={y + 6} x2={x + w - 8} y2={y + 6} /><line x1={x + 8} y1={y + 12} x2={x + w - 8} y2={y + 12} /></> : id === 'pier' ? <rect x={x + w * .2} y={y} width={w * .6} height={h} /> : id === 'foundation' ? <rect x={x} y={y} width={w} height={h} /> : <rect x={x} y={y} width={w} height={h} rx="2" />}{label && <text className="assembly-component-label" stroke="none" strokeWidth="0" paintOrder="normal" x={x + w / 2} y={y + h / 2 + 5} textAnchor="middle">{label}</text>}</g>
  return <div className="spn-assembly-diagram"><svg className="spn-assembly-svg" viewBox="0 0 760 680" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`${definition.kind} engineering schematic`}><line className="spn-svg-centerline" x1="380" y1="90" x2="380" y2="665" />
    <g className="spn-svg-ground"><line x1="70" y1="105" x2="690" y2="105" /><text className="assembly-component-label" stroke="none" strokeWidth="0" paintOrder="normal" x="380" y="82" textAnchor="middle">RED LEVEL</text><line x1="70" y1="145" x2="690" y2="145" strokeDasharray="8 7" /><text className="assembly-component-label" stroke="none" strokeWidth="0" paintOrder="normal" x="380" y="137" textAnchor="middle">PAVEMENT</text></g>
    <Box id="deck" x={110} y={165} w={540} h={32} label="DECK / SLAB" route={node('deck').familyRoute} />
    {definition.kind === 'PIER' ? <><Box id="girder" x={185} y={215} w={155} h={76} label="GIRDER" route={node('girder').familyRoute} /><Box id="girder" x={420} y={215} w={155} h={76} label="GIRDER" route={node('girder').familyRoute} /><Box id="bearing" x={230} y={315} w={55} h={18} label="BEARING" route={node('bearing').familyRoute} /><Box id="bearing" x={475} y={315} w={55} h={18} label="BEARING" route={node('bearing').familyRoute} /><Box id="pier-cap" x={210} y={365} w={340} h={42} label="PIER CAP" route={node('pier-cap').familyRoute} /><Box id="pier" x={305} y={430} w={150} h={125} label="PIER" route={node('pier').familyRoute} /><Box id="foundation" x={130} y={585} w={500} h={42} label="FOUNDATION" route={node('foundation').familyRoute} /><g className={`spn-svg-element${selected('piles')}`} onClick={() => hit('piles', node('piles').familyRoute)}><rect x="220" y="627" width="28" height="38" /><rect x="366" y="627" width="28" height="38" /><rect x="502" y="627" width="28" height="38" /><text className="assembly-component-label" stroke="none" strokeWidth="0" paintOrder="normal" x="380" y="678" textAnchor="middle">PILES</text></g></> : <><Box id="girder" x={250} y={215} w={260} h={55} label="GIRDER" route={node('girder').familyRoute} /><Box id="bearing" x={352} y={292} w={56} h={18} label="BEARING" route={node('bearing').familyRoute} /><Box id="backwall" x={410} y={330} w={150} h={70} label="BACKWALL" /><Box id="front-wall" x={250} y={330} w={150} h={175} label="FRONT WALL" route={node('front-wall').familyRoute} /><Box id="foundation" x={150} y={535} w={460} h={45} label="FOUNDATION" route={node('foundation').familyRoute} /><g className={`spn-svg-element${selected('piles')}`} onClick={() => hit('piles', node('piles').familyRoute)}><line x1="240" y1="580" x2="240" y2="665" /><line x1="380" y1="580" x2="380" y2="665" /><line x1="520" y1="580" x2="520" y2="665" /><text className="assembly-component-label" stroke="none" strokeWidth="0" paintOrder="normal" x="380" y="678" textAnchor="middle">PILES</text></g></>}
  </svg></div>
}

export default function SystemAssemblyPanel() {
  void GirderSpanInspector
  void PierInspector
  const [kind, setKind] = useState<'PIER' | 'ABUTMENT'>('PIER')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [pierCapFamilies, setPierCapFamilies] = useState<PierCapFamily[]>(readPierCapFamilies)
  const [bearingFamilies, setBearingFamilies] = useState<BearingFamily[]>(readBearingFamilies)
  useEffect(() => { const refresh = () => setPierCapFamilies(readPierCapFamilies()); window.addEventListener('storage', refresh); window.addEventListener('spanova:pier-cap-catalog-changed', refresh); return () => { window.removeEventListener('storage', refresh); window.removeEventListener('spanova:pier-cap-catalog-changed', refresh) } }, [])
  useEffect(() => { const refresh = () => setBearingFamilies(readBearingFamilies()); window.addEventListener('storage', refresh); window.addEventListener('spanova:bearing-catalog-changed', refresh); return () => { window.removeEventListener('storage', refresh); window.removeEventListener('spanova:bearing-catalog-changed', refresh) } }, [])
  const definition = kind === 'PIER' ? PIER_ASSEMBLY : ABUTMENT_ASSEMBLY
  const hasPierCapCatalog = pierCapFamilies.some((family) => generatePierCapVariants(family).length > 0)
  const usableBearings = bearingFamilies.filter((family) => family.enabled && bearingStatus(family) === 'VALID')
  const selected = definition.nodes.find((node) => node.id === selectedId)
  const girderVariants = generatePrecastGirderVariants(readGirderDimensions())
  const spanRules = readSpanRules()
  const selectKind = (next: 'PIER' | 'ABUTMENT') => { setKind(next); setSelectedId(null) }
  const left = <div><div className="spn-workspace-heading">SYSTEM ASSEMBLY</div><div className="spn-workspace-tabs"><button className={kind === 'PIER' ? 'active' : ''} onClick={() => selectKind('PIER')}>Pier Assembly</button><button className={kind === 'ABUTMENT' ? 'active' : ''} onClick={() => selectKind('ABUTMENT')}>Abutment Assembly</button></div><div className="spn-workspace-heading">ASSEMBLY COMPONENTS</div>{definition.nodes.map((node) => <button key={node.id} className={`spn-workspace-link${selectedId === node.id ? ' active' : ''}`} onClick={() => setSelectedId(node.id)}>{node.label}<small>{node.id === 'pier-cap' && kind === 'PIER' ? (hasPierCapCatalog ? 'CATALOG' : 'NOT CONFIGURED') : node.id === 'bearing' ? (usableBearings.length ? 'CATALOG' : 'NOT CONFIGURED') : node.status.replaceAll('_', ' ')}</small></button>)}</div>
  const right = <div><h2 className="spn-card-title">Inspector</h2><p className="spn-card-subtitle">Context-sensitive assembly information</p>{selected?.id === 'girder' ? <GirderInspector variants={girderVariants} rules={spanRules} /> : selected?.id === 'bearing' ? <BearingInspector families={bearingFamilies} /> : selected?.id === 'pier-cap' && kind === 'PIER' ? <PierCapInspector families={pierCapFamilies} /> : selected?.id === 'pier' ? <PierInspector /> : selected ? <><div className="spn-inspector-title">{selected.label}</div><div className="spn-inspector-row"><span>Status</span><strong>{selected.status.replaceAll('_', ' ')}</strong></div><p className="spn-inspector-note">{selected.note ?? (selected.familyRoute ? 'Design System family navigation available.' : 'Bridge-specific geometry is derived in Bridge Layout.')}</p>{selected.familyRoute && <OpenFamilyButton route={selected.familyRoute} label={selected.label} />}</> : <div className="spn-status-panel"><strong>NO COMPONENT SELECTED</strong><span>Select a schematic component to inspect it.</span></div>}</div>
  return <div className="spn-workspace-page"><h1>System Assembly</h1><p className="spn-card-subtitle">Design System / canonical vertical system definition</p><EngineeringWorkspace left={left} center={<Assembly definition={definition} selectedId={selectedId} onSelect={setSelectedId} />} right={right} /></div>
}

function readGirderDimensions() { try { return (JSON.parse(localStorage.getItem('spanova.girder-library.precast') ?? 'null') as { dimensions?: typeof PRECAST_DIMENSIONS } | null)?.dimensions ?? PRECAST_DIMENSIONS } catch { return PRECAST_DIMENSIONS } }
function readSpanRules(): PreferredSpanRule[] { try { return JSON.parse(localStorage.getItem('spanova.project-design-system.girder-span-rules') ?? '[]') as PreferredSpanRule[] } catch { return [] } }
function readPierCapFamilies(): PierCapFamily[] { try { return JSON.parse(localStorage.getItem('spanova.project-design-system.pier-cap-families') ?? '[]') as PierCapFamily[] } catch { return [] } }
function readBearingFamilies(): BearingFamily[] { try { return JSON.parse(localStorage.getItem('spanova.project-design-system.bearing-families') ?? '[]') as BearingFamily[] } catch { return [] } }
function spans(rule?: PreferredSpanRule) { if (!rule || rule.spanDelta <= 0 || rule.maxSpan < rule.minSpan) return []; return Array.from({ length: Math.floor((rule.maxSpan - rule.minSpan) / rule.spanDelta) + 1 }, (_, i) => Number((rule.minSpan + i * rule.spanDelta).toFixed(3))) }
function GirderSpanInspector({ variants, rules }: { variants: ReturnType<typeof generatePrecastGirderVariants>; rules: PreferredSpanRule[] }) {
  const navigate = useNavigate()
  return <><div className="spn-inspector-title">GIRDER</div><div className="spn-inspector-label">Girder Family</div><select className="spn-input" defaultValue="PRECAST_GIRDER"><option value="PRECAST_GIRDER">Precast Girder</option></select><h3 className="spn-inspector-section">Available Variants: {variants.length}</h3><table className="spn-inspector-table"><thead><tr><th>Variant</th><th>H</th><th>Status</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id}><td>{variant.label.replace('PG-', '')}</td><td>{variant.heightCm} cm</td><td>VALID</td></tr>)}</tbody></table><h3 className="spn-inspector-section">Preferred Spans</h3><table className="spn-inspector-table"><thead><tr><th>Variant</th><th>Span Values</th><th>Primary</th></tr></thead><tbody>{variants.map((variant) => { const rule = rules.find((item) => item.girderVariantId === variant.id); const values = spans(rule); return <tr key={variant.id}><td>{variant.label.replace('PG-', '')}</td><td>{values.length ? values.join(', ') : 'NOT CONFIGURED'}</td><td>{rule && values.includes(rule.primarySpan) ? `${rule.primarySpan} m` : 'ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â'}</td></tr> })}</tbody></table><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/girder-library')}>Open Girder</button></>
}

function GirderInspector({ variants, rules }: { variants: ReturnType<typeof generatePrecastGirderVariants>; rules?: PreferredSpanRule[] }) {
  const navigate = useNavigate()
  const [family, setFamily] = useState('PRECAST_GIRDER')
  if (family !== 'PRECAST_GIRDER') return <><div className="spn-inspector-title">GIRDER</div><div className="spn-inspector-label">Girder Family</div><select className="spn-input" value={family} onChange={(event) => setFamily(event.target.value)}><option value="PRECAST_GIRDER">Precast Girder</option><option value="STEEL_GIRDER">Steel Girder</option><option value="BOX_GIRDER">Box Girder</option></select><p className="spn-inspector-note">No generated {family === 'STEEL_GIRDER' ? 'Steel' : 'Box'} Girder variants available. Status: NOT CONFIGURED</p><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/girder-library')}>Open Girder</button></>
  return <><div className="spn-inspector-title">GIRDER</div><div className="spn-inspector-label">Girder Family</div><select className="spn-input" value={family} onChange={(event) => setFamily(event.target.value)}><option value="PRECAST_GIRDER">Precast Girder</option><option value="STEEL_GIRDER">Steel Girder</option><option value="BOX_GIRDER">Box Girder</option></select><h3 className="spn-inspector-section">GENERATED VARIANTS ({variants.length})</h3><table className="spn-inspector-table"><thead><tr><th>Variant</th><th>H</th><th>Status</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id}><td>{variant.label}</td><td>{variant.heightCm} cm</td><td>VALID</td></tr>)}</tbody></table><h3 className="spn-inspector-section">PREFERRED SPANS</h3><table className="spn-inspector-table"><thead><tr><th>Variant</th><th>Values</th><th>Primary</th></tr></thead><tbody>{variants.map((variant) => { const rule = rules?.find((item) => item.girderVariantId === variant.id); const values = spans(rule); return <tr key={variant.id}><td>{variant.label}</td><td>{values.length ? values.join(', ') : 'NOT CONFIGURED'}</td><td>{rule && values.includes(rule.primarySpan) ? `${rule.primarySpan} m` : 'NOT CONFIGURED'}</td></tr> })}</tbody></table><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/girder-library')}>Open Girder</button></>
}

function PierInspector() {
  const navigate = useNavigate()
  const [selectedId, setSelectedId] = useState('')
  let families: PierFamily[] = []
  try { families = JSON.parse(localStorage.getItem('spanova.project-design-system.pier-families') ?? '[]') as PierFamily[] } catch { /* empty catalog */ }
  const family = families.find((item) => item.id === selectedId) ?? families[0]
  if (!family) return <><div className="spn-inspector-title">PIER</div><p className="spn-inspector-note">No Pier Family configured.</p><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/pier-families')}>Open Pier</button></>
  const variants = generatePierVariants(family)
  const configs = family.allowedConfigurations.filter((configuration) => configuration === 'SINGLE_COLUMN' || configuration === 'TWO_COLUMNS')
  return <><div className="spn-inspector-title">PIER</div><div className="spn-inspector-label">Pier Family</div><select className="spn-input" value={family.id} onChange={(event) => setSelectedId(event.target.value)}>{families.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><h3 className="spn-inspector-section">TYPE / STATUS</h3><div className="spn-inspector-row"><span>Type</span><strong>{family.pierType}</strong></div><div className="spn-inspector-row"><span>Status</span><strong>{family.enabled ? 'ENABLED' : 'DISABLED'}</strong></div><h3 className="spn-inspector-section">SECTION VARIANTS ({variants.length})</h3><table className="spn-inspector-table spn-pier-variant-table"><thead><tr><th>Variant</th><th>B (m)</th><th>D (m)</th><th>tw (m)</th></tr></thead><tbody>{variants.slice(0, 24).map((variant, index) => <tr key={variant.id}><td>P{String(index + 1).padStart(2, '0')}</td><td>{formatPierValue(variant.sectionParameters.B)}</td><td>{formatPierValue(variant.sectionParameters.D)}</td><td>{formatPierValue(variant.sectionParameters.tw)}</td></tr>)}</tbody></table><h3 className="spn-inspector-section">CONFIGURATIONS</h3><p className="spn-inspector-note">{configs.join(' / ') || 'NOT CONFIGURED'}</p>{configs.includes('TWO_COLUMNS') && family.twoColumnSpacing && <><h3 className="spn-inspector-section">TWO-COLUMN SPACING</h3><p className="spn-inspector-note">{family.twoColumnSpacing.min} - {family.twoColumnSpacing.max} m (delta {family.twoColumnSpacing.delta} m)</p></>}<h3 className="spn-inspector-section">HEIGHT APPLICABILITY</h3><p className="spn-inspector-note">Minimum: {family.heightApplicability.minimumHeight} m<br />Preferred: {family.heightApplicability.preferredHeightMin} - {family.heightApplicability.preferredHeightMax} m<br />Maximum: {family.heightApplicability.maximumHeight} m</p><p className="spn-inspector-note">Actual Pier Height: DERIVED IN BRIDGE LAYOUT</p><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/pier-families')}>Open Pier</button></>
}
function PierCapInspector({ families }: { families: PierCapFamily[] }) {
  const navigate = useNavigate()
  const usableFamilies = families.filter((family) => generatePierCapVariants(family).length > 0)
  const [selectedId, setSelectedId] = useState(usableFamilies[0]?.id ?? '')
  const family = usableFamilies.find((item) => item.id === selectedId) ?? usableFamilies[0]
  useEffect(() => { if (!usableFamilies.some((item) => item.id === selectedId)) setSelectedId(usableFamilies[0]?.id ?? '') }, [families, selectedId])
  if (!family) return <><div className="spn-inspector-title">PIER CAP</div><p className="spn-inspector-note">No enabled Pier Cap Family configured.</p><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/pier-cap-families')}>Open Pier Cap</button></>
  const variants = generatePierCapVariants(family)
  return <><div className="spn-inspector-title">PIER CAP</div><div className="spn-inspector-label">Pier Cap Family</div><select className="spn-input" value={family.id} onChange={(event) => setSelectedId(event.target.value)}>{usableFamilies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><h3 className="spn-inspector-section">TYPE / STATUS</h3><div className="spn-inspector-row"><span>Type</span><strong>{family.capType}</strong></div><div className="spn-inspector-row"><span>Configuration</span><strong>{family.compatiblePierConfiguration}</strong></div><div className="spn-inspector-row"><span>Structural System</span><strong>{structuralSystem(family.compatiblePierConfiguration)}</strong></div><div className="spn-inspector-row"><span>Status</span><strong>{family.enabled ? 'ENABLED' : 'DISABLED'}</strong></div><h3 className="spn-inspector-section">SECTION VARIANTS ({variants.length})</h3><table className="spn-inspector-table spn-pier-variant-table"><thead><tr><th>Variant</th><th>Transverse Length</th><th>Structural Height</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id}><td>{`${family.name}-L${formatEngineeringValue(variant.capTransverseLength)}-H${formatEngineeringValue(variant.capStructuralHeight)}`}</td><td>{formatEngineeringValue(variant.capTransverseLength)} m</td><td>{formatEngineeringValue(variant.capStructuralHeight)} m</td></tr>)}</tbody></table><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/pier-cap-families')}>Open Pier Cap</button></>
}
function BearingInspector({ families }: { families: BearingFamily[] }) {
  const navigate = useNavigate()
  const usable = families.filter((family) => family.enabled && bearingStatus(family) === 'VALID')
  const [selectedId, setSelectedId] = useState(usable[0]?.id ?? '')
  const family = usable.find((item) => item.id === selectedId) ?? usable[0]
  useEffect(() => { if (!usable.some((item) => item.id === selectedId)) setSelectedId(usable[0]?.id ?? '') }, [families, selectedId])
  if (!family) return <><div className="spn-inspector-title">BEARING</div><p className="spn-inspector-note">No enabled, valid Bearing Family configured.</p><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/bearing-families')}>Open Bearing</button></>
  const variants = generateBearingVariants(family)
  return <><div className="spn-inspector-title">BEARING</div><div className="spn-inspector-label">Bearing Family</div><select className="spn-input" value={family.id} onChange={(event) => setSelectedId(event.target.value)}>{usable.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><h3 className="spn-inspector-section">TYPE / STATUS</h3><div className="spn-inspector-row"><span>Type</span><strong>{family.bearingType}</strong></div><div className="spn-inspector-row"><span>Status</span><strong>ENABLED</strong></div><h3 className="spn-inspector-section">GEOMETRY VARIANTS ({variants.length})</h3><table className="spn-inspector-table spn-pier-variant-table"><thead><tr><th>Variant</th><th>L (mm)</th><th>B (mm)</th><th>H (mm)</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id}><td>{`${family.name}-L${displayValue(variant.length)}-B${displayValue(variant.width)}-H${displayValue(variant.height)}`}</td><td>{displayValue(variant.length)}</td><td>{displayValue(variant.width)}</td><td>{displayValue(variant.height)}</td></tr>)}</tbody></table><button className="spn-button-secondary spn-inspector-open" onClick={() => navigate('/bearing-families')}>Open Bearing</button></>
}
function formatEngineeringValue(value: number) { return Number.isInteger(value) ? String(value) : String(Number(value.toFixed(3))) }

function formatPierValue(value: number | undefined) { return value == null ? '—' : value.toFixed(1) }
function OpenFamilyButton({ route, label }: { route: string; label: string }) {
  const navigate = useNavigate()
  return <button className="spn-button-secondary spn-inspector-open" onClick={() => navigate(`/${route}`)}>Open {label}</button>
}
