import type { SpanovaNode, GraphExecutionState, GraphValue, MaterialValue, PierCandidate, PierCapCandidate, FoundationCandidate, SpanovaConnection } from '../domain/types'
import { getNodeDefinition, previewDesignOutput, previewPierCapStatistics, previewFoundationStatistics } from '../registry/nodeRegistry'
import { getUnit, unitsForKind } from '../domain/quantities'
import { formatQuantity, formatQuantityList, quantityFromCanonical as importQuantityFromCanonical } from '../domain/quantities'
import EditableNumericInput from './EditableNumericInput'

export default function NodeInspector({ node, states, errors, outputs, resolvedInputs = {}, previewInputs = {}, nodes = [], connections = [], concreteMaterial, onNodeChange, onParameterChange }: { node?: SpanovaNode; states: Record<string, GraphExecutionState>; errors: Record<string, string>; outputs: Record<string, Record<string, GraphValue>>; resolvedInputs?: Record<string, Record<string, GraphValue>>; previewInputs?: Record<string,{sourceName:string;value?:GraphValue;error?:string}>; nodes?: SpanovaNode[]; connections?: SpanovaConnection[]; concreteMaterial?: MaterialValue; onNodeChange: (id: string, patch: Partial<SpanovaNode>) => void; onParameterChange: (id: string, key: string, value: number | boolean | string) => void }) {
  if (!node) return <div className="spn-graph-inspector-empty">Select a node to inspect its parameters and ports.</div>
  const definition = getNodeDefinition(node.type)
  if (!definition) return <p role="alert">Unknown node type: {node.type}</p>
  const state = states[node.id] ?? 'idle'
  const candidates = node.type.startsWith('substructure.pier.') ? asPierCandidates(outputs[node.id]?.candidates) : []
  const isPierCap = node.type.startsWith('substructure.pier-cap.')
  const capInputs = Object.fromEntries(Object.entries(previewInputs).flatMap(([key, value]) => value.value === undefined ? [] : [[key, value.value]]))
  const capCandidates = isPierCap ? safeCapCandidates(node, capInputs, outputs[node.id]?.candidates) : []
  const capDisplayGeometry = isPierCap ? capGeometryForDisplay(node, capInputs, capCandidates[0]?.geometry) : undefined
  const capStatistics = isPierCap ? safeCapStatistics(node, capInputs, capCandidates.length) : undefined
  const isFoundation=node.type.startsWith('substructure.foundation.')
  const foundationInputs=Object.fromEntries(Object.entries(previewInputs).flatMap(([key,value])=>value.value===undefined?[]:[[key,value.value]]))
  const foundationCandidates=isFoundation?safeFoundationCandidates(node,foundationInputs,outputs[node.id]?.candidates):[]
  const foundationPreviewError=isFoundation?safeFoundationPreviewError(node,foundationInputs):undefined
  const foundationStatistics=isFoundation?safeFoundationStatistics(node,foundationInputs,foundationCandidates.length):undefined
  return <div className="spn-graph-inspector">
    <section><h3>GENERAL</h3><label>Name<input className="spn-input" value={node.name} onChange={(event) => onNodeChange(node.id, { name: event.target.value })} /></label><div className="spn-graph-inspector-row"><span>Type</span><code>{node.type}</code></div><div className="spn-graph-inspector-row"><span>ID</span><code title={node.id}>{node.id}</code></div><div className="spn-graph-inspector-row"><span>Execution</span><strong className={`state-${state}`}>{state.toUpperCase()}</strong></div>{errors[node.id] && <p className="spn-graph-inspector-error">{errors[node.id]}</p>}</section>
    {node.type === 'material.concrete' && <section><h3>CONCRETE MATERIAL</h3><div className="spn-graph-inspector-row"><span>Material Type</span><strong>Concrete</strong></div><div className="spn-graph-inspector-row"><span>Grade</span><strong>{String(node.parameters.materialId ?? 'C40/50')}</strong></div>{concreteMaterial ? concretePropertyRows(concreteMaterial) : <small>Loading authoritative material properties...</small>}</section>}
    {isPierCap && <section><h3>FAMILY</h3><div className="spn-graph-inspector-row"><span>Cap Type</span><strong>{node.type.endsWith('.t') ? 'T-Cap' : 'Rectangular Cap'}</strong></div><CapSchematic type={node.type} values={capDisplayGeometry} /><div className="spn-graph-inspector-row"><span>Material</span><strong>{capCandidates[0]?.material.name ?? capMaterialName(capInputs.material) ?? String(node.parameters.materialId ?? 'C40/50')}</strong></div><div className="spn-graph-inspector-row"><span>Raw combinations</span><strong>{capStatistics?.generatedCombinations ?? 0}</strong></div><div className="spn-graph-inspector-row"><span>Valid candidates</span><strong>{capCandidates.length}</strong></div><div className="spn-graph-inspector-row"><span>Invalid combinations</span><strong>{capStatistics?.invalidCombinations ?? 0}</strong></div><div className="spn-graph-inspector-row"><span>Geometry validation</span><strong>{errors[node.id] ? 'FAILED' : capStatistics?.invalidCombinations ? 'INVALID COMBINATIONS FILTERED' : capCandidates.length ? 'VALID' : 'NO VALID CANDIDATES'}</strong></div>{capCandidates.slice(0,10).map((candidate,index)=><div className="spn-graph-inspector-row" key={candidate.id}><span>{index+1}. {summarizeCap(candidate)}</span></div>)}{capCandidates.length>10&&<small>Showing 10 of {capCandidates.length} candidates.</small>}</section>}
    {isFoundation&&<section><h3>FOUNDATION</h3><div className="spn-graph-inspector-row"><span>Foundation Type</span><strong>{node.type.endsWith('.shallow')?'Shallow':'Piled'}</strong></div><FoundationSchematic piled={node.type.endsWith('.piled')} candidates={foundationCandidates}/><div className="spn-graph-inspector-row"><span>Material</span><strong>{foundationCandidates[0]?.material.name??capMaterialName(foundationInputs.material)??String(node.parameters.materialId??'C40/50')}</strong></div>{node.type.endsWith('.piled')&&<><div className="spn-graph-inspector-row"><span>Derived Lx</span><strong>{derivedSummary(foundationCandidates,'Lx')}</strong></div><div className="spn-graph-inspector-row"><span>Derived Ly</span><strong>{derivedSummary(foundationCandidates,'Ly')}</strong></div></>}<div className="spn-graph-inspector-row"><span>Raw combinations</span><strong>{foundationStatistics?.generatedCombinations??0}</strong></div><div className="spn-graph-inspector-row"><span>Valid candidates</span><strong>{foundationCandidates.length}</strong></div><div className="spn-graph-inspector-row"><span>Invalid combinations</span><strong>{foundationPreviewError?'—':foundationStatistics?.invalidCombinations??0}</strong></div><div className="spn-graph-inspector-row"><span>Geometry validation</span><strong>{errors[node.id]||foundationPreviewError?'FAILED':foundationStatistics?.invalidCombinations?'INVALID COMBINATIONS FILTERED':foundationCandidates.length?'VALID':'NO VALID CANDIDATES'}</strong></div>{foundationPreviewError&&<small role="alert">{foundationPreviewError}</small>}{foundationCandidates.slice(0,10).map((candidate,index)=><div className="spn-graph-inspector-row" key={candidate.id}><span>{index+1}. {summarizeFoundation(candidate)}</span></div>)}{foundationCandidates.length>10&&<small>Showing 10 of {foundationCandidates.length} candidates.</small>}</section>}
    {node.type !== 'material.concrete' && (<section><h3>PARAMETERS</h3>{definition.parameterSchema.length ? definition.parameterSchema.map((parameter) => { const units = parameter.key === 'unit' ? unitsForKind(node.parameters.quantityKind as import('../domain/quantities').QuantityKind) : []; const options = parameter.key === 'unit' ? units.map(unit => ({value:unit.id,label:unit.label})) : parameter.options ?? []; const overridden = parameter.inputPortId ? connections.some(edge => edge.targetNodeId === node.id && edge.targetPortId === parameter.inputPortId) : false; return <label key={parameter.key} style={overridden ? { opacity: .5 } : undefined}>{parameter.label}{overridden ? ' · connected' : ''}{parameter.dataType === 'boolean' ? <input type="checkbox" checked={Boolean(node.parameters[parameter.key])} disabled={overridden} onChange={(event) => onParameterChange(node.id, parameter.key, event.target.checked)} /> : parameter.dataType === 'select' ? <select className="spn-input" aria-label={parameter.label} value={String(node.parameters[parameter.key] ?? options[0]?.value ?? '')} disabled={!options.length || overridden} onChange={(event) => { onParameterChange(node.id, parameter.key, event.target.value); if(parameter.key==='quantityKind'){const nextUnit=unitsForKind(event.target.value as import('../domain/quantities').QuantityKind)[0]?.id;if(nextUnit)onParameterChange(node.id,'unit',nextUnit)} }}><option value="" disabled>{options.length?'Select…':'No supported materials configured'}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select> : parameter.dataType === 'string' ? <input className="spn-input" value={String(node.parameters[parameter.key] ?? '')} disabled={overridden} onChange={event=>onParameterChange(node.id,parameter.key,event.target.value)} /> : <EditableNumericInput value={node.parameters[parameter.key]} integer={parameter.dataType === 'integer'} disabled={overridden} ariaLabel={parameter.label} onCommit={value => onParameterChange(node.id, parameter.key, value)} />}</label>}) : <small>No editable parameters.</small>}</section>)}
      <section><h3>PORTS</h3><strong className="spn-graph-port-heading">INPUTS</strong>{definition.inputs.length ? definition.inputs.map((port) => { const connection=connections.find(item=>item.targetNodeId===node.id&&item.targetPortId===port.id);const source=connection&&nodes.find(item=>item.id===connection.sourceNodeId);const sourcePort=source&&getNodeDefinition(source.type)?.outputs.find(item=>item.id===connection?.sourcePortId);const resolved=resolvedInputs[node.id]?.[port.id]??previewInputs[port.id]?.value;return <div className="spn-graph-inspector-input" key={port.id}><div className="spn-graph-inspector-row" title={port.description}><span>{port.label} · {source&&sourcePort?`Source: ${source.name}.${sourcePort.label}`:'Source: local default'}{resolved!==undefined?` · Resolved: ${formatResolved(resolved)}`:''}</span><code title={port.description}>{port.type}</code></div>{connection&&Array.isArray(resolved)&&<ResolvedListDetails value={resolved} quantityLabel={source?.parameters.quantityKind} />}</div>}) : <small>None</small>}<strong className="spn-graph-port-heading">OUTPUTS</strong>{definition.outputs.length ? definition.outputs.map((port) => <div className="spn-graph-inspector-row" key={port.id}><span>{port.label}{outputs[node.id]?.[port.id] !== undefined ? ` · ${format(outputs[node.id][port.id])}` : ''}</span><code>{port.type}</code></div>) : <small>None</small>}</section>
    {node.type.startsWith('substructure.pier.') && <section><h3>PIER GENERATION</h3><div className="spn-graph-inspector-row"><span>Candidate count</span><strong>{candidates.length}</strong></div>{outputs[node.id]?.generatedCombinations !== undefined && <div className="spn-graph-inspector-row"><span>Generated combinations</span><strong>{format(outputs[node.id].generatedCombinations)}</strong></div>}{outputs[node.id]?.invalidCombinations !== undefined && <div className="spn-graph-inspector-row"><span>Invalid geometry</span><strong>{format(outputs[node.id].invalidCombinations)}</strong></div>}<div className="spn-graph-inspector-row"><span>Validation</span><strong>{errors[node.id] ? 'FAILED' : state === 'success' ? (candidates.length ? 'VALID' : 'NO VALID CANDIDATES') : 'NOT RUN'}</strong></div><PierPreview type={node.type} />{candidates.slice(0,10).map((candidate,index)=><div className="spn-graph-inspector-row" key={candidate.id}><span>{index+1}. {candidate.pierType} {Object.entries(candidate.geometry).map(([key,value])=>`${key}=${value.toFixed(2)} m`).join(' ')} H={candidate.heightM.toFixed(2)} m · {candidate.material.name}</span></div>)}{candidates.length>10&&<small>Showing 10 of {candidates.length} candidates.</small>}</section>}
  </div>
}
function ResolvedListDetails({value,quantityLabel}:{value:GraphValue[];quantityLabel?:unknown}){
  const quantities=value.length>0&&value.every(item=>typeof item==='object'&&item!==null&&'quantityKind'in item)?value as import('../domain/quantities').EngineeringQuantity[]:undefined
  const numbers=quantities?.map(item=>item.value)??value.filter((item):item is number=>typeof item==='number')
  const kind=quantities?.[0]?.quantityKind??(typeof quantityLabel==='string'?quantityLabel:undefined)
  const unit=quantities?.[0]?.unit
  const fromCanonical=(number:number)=>quantities&&unit?importQuantityFromCanonical(number,kind as import('../domain/quantities').QuantityKind,unit):number
  return <details className="spn-graph-inspector-list"><summary>Resolved list details · {value.length} values</summary><div><span>Type</span><strong>{quantities?'Quantity List':'Numeric List'}</strong><span>Quantity</span><strong>{kind??'Dimensionless'}</strong><span>Unit</span><strong>{unit??'Project display units at engineering input'}</strong><span>Count</span><strong>{value.length}</strong><span>Min</span><strong>{numbers.length?fromCanonical(Math.min(...numbers)).toFixed(2):'—'}</strong><span>Max</span><strong>{numbers.length?fromCanonical(Math.max(...numbers)).toFixed(2):'—'}</strong><span>Values</span><strong>{quantities?formatQuantityList(quantities):value.map(item=>String(item)).join(', ')}</strong></div></details>
}
  function format(value: GraphValue):string { if(Array.isArray(value)){if(value.every(item=>typeof item==='object'&&item!==null&&'quantityKind'in item)){const list=value as import('../domain/quantities').EngineeringQuantity[];const shown=list.length>20?`${formatQuantityList(list.slice(0,20))} … (${list.length} values)`:formatQuantityList(list);return shown}const preview=value.slice(0,20).map(item=>format(item)).join(', ');return `[${preview}${value.length>20?', …':''}]${value.length>20?` (${value.length} values)`:''}`}if(typeof value==='object'&&value!==null&&'quantityKind'in value)return formatQuantity(value);if(typeof value==='object'&&value!==null&&'domainType'in value){const material=value as import('../domain/types').MaterialValue;const props=Object.entries(material.properties).map(([key,q])=>`${key} ${formatQuantity(q)}`).join(', ');return `${material.domainType} ${material.name}${props?` · ${props}`:''}`}return String(value) }
function asPierCandidates(value:GraphValue|undefined):PierCandidate[]{return Array.isArray(value)&&value.every(item=>typeof item==='object'&&item!==null&&'pierType'in item)?value as PierCandidate[]:[]}
function asPierCapCandidates(value:GraphValue|undefined):PierCapCandidate[]{return Array.isArray(value)&&value.every(item=>typeof item==='object'&&item!==null&&'capType'in item)?value as PierCapCandidate[]:[]}
function safeCapCandidates(node:SpanovaNode,inputs:Record<string,GraphValue>,fallback:GraphValue|undefined){try{return asPierCapCandidates(previewDesignOutput(node,'candidates',inputs))}catch{return asPierCapCandidates(fallback)}}
function safeCapStatistics(node:SpanovaNode,inputs:Record<string,GraphValue>,validCandidates:number){try{return previewPierCapStatistics(node,inputs,validCandidates)}catch{return undefined}}
function asFoundationCandidates(value:GraphValue|undefined):FoundationCandidate[]{return Array.isArray(value)&&value.every(item=>typeof item==='object'&&item!==null&&'foundationType'in item)?value as FoundationCandidate[]:[]}
function safeFoundationCandidates(node:SpanovaNode,inputs:Record<string,GraphValue>,fallback:GraphValue|undefined){try{return asFoundationCandidates(previewDesignOutput(node,'candidates',inputs)??fallback)}catch{return asFoundationCandidates(fallback)}}
function safeFoundationPreviewError(node:SpanovaNode,inputs:Record<string,GraphValue>){try{previewDesignOutput(node,'candidates',inputs);return undefined}catch(error){return error instanceof Error?error.message:String(error)}}
function safeFoundationStatistics(node:SpanovaNode,inputs:Record<string,GraphValue>,validCandidates:number){try{return previewFoundationStatistics(node,inputs,validCandidates)}catch{return undefined}}
function foundationDerived(candidate:FoundationCandidate,axis:'Lx'|'Ly'){return candidate.foundationType==='PILED'?Number((candidate.geometry.derived as Readonly<Record<string,number>>)[axis]):Number(candidate.geometry[axis])}
function derivedSummary(candidates:FoundationCandidate[],axis:'Lx'|'Ly'){if(!candidates.length)return '—';const values=candidates.map(candidate=>foundationDerived(candidate,axis));const min=Math.min(...values),max=Math.max(...values);return min===max?`${min.toFixed(2)} m`:`${min.toFixed(2)}…${max.toFixed(2)} m`}
function summarizeFoundation(candidate:FoundationCandidate){const g=candidate.geometry;return candidate.foundationType==='SHALLOW'?`Shallow Foundation Lx=${Number(g.Lx).toFixed(2)} m Ly=${Number(g.Ly).toFixed(2)} m H=${Number(g.height).toFixed(2)} m · ${candidate.material.name}`:`Piled Foundation D=${Number(g.pileDiameter).toFixed(2)} m nx=${g.pileCountX} ax=${Number(g.pileSpacingX).toFixed(2)} m ny=${g.pileCountY} ay=${Number(g.pileSpacingY).toFixed(2)} m Cap H=${Number(g.capHeight).toFixed(2)} m Lx=${foundationDerived(candidate,'Lx').toFixed(2)} m Ly=${foundationDerived(candidate,'Ly').toFixed(2)} m · ${candidate.material.name}`}
function FoundationSchematic({piled,candidates}:{piled:boolean;candidates:FoundationCandidate[]}){const candidate=candidates[0];if(!candidate)return <small>Schematic preview · waiting for valid inputs</small>;if(!piled){const Lx=Number(candidate.geometry.Lx),Ly=Number(candidate.geometry.Ly),height=Number(candidate.geometry.height);return <div className="spn-graph-foundation-preview"><svg viewBox="0 0 200 126" role="img" aria-label="Shallow Foundation plan and section"><rect x="47" y="24" width="106" height="48"/><text x="100" y="18" textAnchor="middle">Lx {Lx.toFixed(2)} m</text><text x="30" y="50" textAnchor="middle">Ly {Ly.toFixed(2)} m</text><rect x="58" y="94" width="84" height="16"/><text x="150" y="106">H {height.toFixed(2)} m</text></svg><small>Plan and section schematic</small></div>}
 const g=candidate.geometry,d=g.derived as Readonly<Record<string,number>>,nx=Number(g.pileCountX),ny=Number(g.pileCountY);const cols=Math.min(nx,8),rows=Math.min(ny,8),circles=Array.from({length:cols*rows},(_,i)=>{const x=48+(cols===1?0:i%cols/(cols-1)*104),y=25+(rows===1?0:Math.floor(i/cols)/(rows-1)*54);return <circle key={i} cx={x} cy={y} r="4"/>});return <div className="spn-graph-foundation-preview"><svg viewBox="0 0 200 108" role="img" aria-label={`Piled Foundation plan ${nx} by ${ny}`}><rect x="35" y="14" width="130" height="76"/>{circles}</svg><small>{nx} × {ny} pile layout · D {Number(g.pileDiameter).toFixed(2)} m · ax {Number(g.pileSpacingX).toFixed(2)} m · ay {Number(g.pileSpacingY).toFixed(2)} m · Lx {d.Lx.toFixed(2)} m · Ly {d.Ly.toFixed(2)} m</small></div>}
function capMaterialName(value:GraphValue|undefined){return typeof value==='object'&&value!==null&&!Array.isArray(value)&&'domainType'in value?(value as MaterialValue).name:undefined}
function capGeometryForDisplay(node:SpanovaNode,inputs:Record<string,GraphValue>,candidate?:Readonly<Record<string,number>>){if(candidate)return candidate;const keys=node.type.endsWith('.t')?['length','topWidth','stemWidth','totalHeight','flangeThickness']:['length','width','height'];return Object.fromEntries(keys.map(key=>{const raw=inputs[key]??node.parameters[`${key}Value`],first=Array.isArray(raw)?raw[0]:raw;let canonical=0;if(typeof first==='number'){const unit=getUnit(String(node.parameters[`${key}Unit`]??'m'));canonical=unit?.kind==='length'?unit.toCanonical(first):first}else if(typeof first==='object'&&first!==null&&'quantityKind'in first&&first.quantityKind==='length')canonical=first.value;return[key,canonical]}))}
function summarizeCap(candidate:PierCapCandidate){const g=candidate.geometry;return candidate.capType==='T'?`T-Cap L=${g.length.toFixed(2)} m Top W=${g.topWidth.toFixed(2)} m Stem W=${g.stemWidth.toFixed(2)} m H=${g.totalHeight.toFixed(2)} m tf=${g.flangeThickness.toFixed(2)} m · ${candidate.material.name}`:`Rectangular Cap L=${g.length.toFixed(2)} m W=${g.width.toFixed(2)} m H=${g.height.toFixed(2)} m · ${candidate.material.name}`}
function CapSchematic({type,values}:{type:string;values?:Readonly<Record<string,number>>}){const t=type.endsWith('.t');return <div className="spn-graph-cap-preview"><svg viewBox="0 0 180 112" role="img" aria-label={t?'Illustrative T-Cap cross section':'Illustrative Rectangular Cap cross section'}><path d={t?'M42 18H138V42H104V94H76V42H42Z':'M42 20H138V92H42Z'} /><text x="90" y="108" textAnchor="middle">{t?`Top W ${values?.topWidth?.toFixed(2)??'—'} m · Stem W ${values?.stemWidth?.toFixed(2)??'—'} m`:`Width ${values?.width?.toFixed(2)??'—'} m`}</text><text x="146" y="58">{t?`H ${values?.totalHeight?.toFixed(2)??'—'} m`:`H ${values?.height?.toFixed(2)??'—'} m`}</text>{t&&<text x="90" y="12" textAnchor="middle">tf {values?.flangeThickness?.toFixed(2)??'—'} m</text>}</svg><small>Illustrative section · Length {values?.length?.toFixed(2)??'—'} m</small></div>}
function formatResolved(value:GraphValue):string { if(Array.isArray(value)){const preview=value.slice(0,3).map(item=>format(item)).join(', ');return `${preview}${value.length>3?'… ':''} (${value.length} values)`}return format(value) }
function PierPreview({type}:{type:string}){const shape=type.includes('circular')?<circle cx="60" cy="42" r="25"/>:type.includes('box')?<path d="M25 17h70v50H25z M37 29h46v26H37z" fillRule="evenodd"/>:type.includes('oval')?<rect x="25" y="24" width="70" height="36" rx="18"/>:type.includes('h_section')?<path d="M32 17h56v14H69v22h19v14H32V53h19V31H32z"/>:<rect x="30" y="17" width="60" height="50"/>;return <svg viewBox="0 0 120 84" role="img" aria-label={`${type.replace('substructure.pier.','')} pier cross section`} style={{width:120,height:84,fill:'rgba(76,145,255,.2)',stroke:'#4c91ff',strokeWidth:2}}>{shape}</svg>}

function concretePropertyRows(material: MaterialValue) {
  const labels: Record<string, string> = { fck: 'fck', fcm: 'fcm', Ecm: 'Ecm', unitWeight: 'Unit weight', density: 'Mass density', poissonRatioUncracked: 'Poisson ratio' }
  const keys = ['fck', 'fcm', 'Ecm', 'unitWeight', 'density', 'poissonRatioUncracked']
  return keys.filter(key => material.properties[key]).map(key => <div className="spn-graph-inspector-row" key={key}><span>{labels[key]}</span><strong>{formatQuantity(material.properties[key])}</strong></div>)
}
