import type { SpanovaNode, GraphExecutionState, GraphValue } from '../domain/types'
import { getNodeDefinition } from '../registry/nodeRegistry'
import { unitsForKind } from '../domain/quantities'
import { formatQuantity, formatQuantityList } from '../domain/quantities'

export default function NodeInspector({ node, states, errors, outputs, onNodeChange, onParameterChange }: { node?: SpanovaNode; states: Record<string, GraphExecutionState>; errors: Record<string, string>; outputs: Record<string, Record<string, GraphValue>>; onNodeChange: (id: string, patch: Partial<SpanovaNode>) => void; onParameterChange: (id: string, key: string, value: number | boolean | string) => void }) {
  if (!node) return <div className="spn-graph-inspector-empty">Select a node to inspect its parameters and ports.</div>
  const definition = getNodeDefinition(node.type)
  if (!definition) return <p role="alert">Unknown node type: {node.type}</p>
  const state = states[node.id] ?? 'idle'
  return <div className="spn-graph-inspector">
    <section><h3>GENERAL</h3><label>Name<input className="spn-input" value={node.name} onChange={(event) => onNodeChange(node.id, { name: event.target.value })} /></label><div className="spn-graph-inspector-row"><span>Type</span><code>{node.type}</code></div><div className="spn-graph-inspector-row"><span>ID</span><code title={node.id}>{node.id}</code></div><div className="spn-graph-inspector-row"><span>Execution</span><strong className={`state-${state}`}>{state.toUpperCase()}</strong></div>{errors[node.id] && <p className="spn-graph-inspector-error">{errors[node.id]}</p>}</section>
    <section><h3>PARAMETERS</h3>{definition.parameterSchema.length ? definition.parameterSchema.map((parameter) => { const units = parameter.key === 'unit' ? unitsForKind(node.parameters.quantityKind as import('../domain/quantities').QuantityKind) : []; const options = parameter.key === 'unit' ? units.map(unit => ({value:unit.id,label:unit.label})) : parameter.options ?? []; return <label key={parameter.key}>{parameter.label}{parameter.dataType === 'boolean' ? <input type="checkbox" checked={Boolean(node.parameters[parameter.key])} onChange={(event) => onParameterChange(node.id, parameter.key, event.target.checked)} /> : parameter.dataType === 'select' ? <select className="spn-input" aria-label={parameter.label} value={String(node.parameters[parameter.key] ?? options[0]?.value ?? '')} disabled={!options.length} onChange={(event) => { onParameterChange(node.id, parameter.key, event.target.value); if(parameter.key==='quantityKind'){const nextUnit=unitsForKind(event.target.value as import('../domain/quantities').QuantityKind)[0]?.id;if(nextUnit)onParameterChange(node.id,'unit',nextUnit)} }}><option value="" disabled>{options.length?'Select…':'No supported materials configured'}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select> : parameter.dataType === 'string' ? <input className="spn-input" value={String(node.parameters[parameter.key] ?? '')} onChange={event=>onParameterChange(node.id,parameter.key,event.target.value)} /> : <input className="spn-input" type="number" step={parameter.step ?? (parameter.dataType === 'integer' ? 1 : 'any')} value={typeof node.parameters[parameter.key] === 'number' ? node.parameters[parameter.key] as number : ''} onChange={(event) => { const value = event.target.valueAsNumber; if (Number.isFinite(value)) onParameterChange(node.id, parameter.key, parameter.dataType === 'integer' ? Math.trunc(value) : value) }} />}</label>}) : <small>No editable parameters.</small>}</section>
    <section><h3>PORTS</h3><strong className="spn-graph-port-heading">INPUTS</strong>{definition.inputs.length ? definition.inputs.map((port) => <div className="spn-graph-inspector-row" key={port.id}><span>{port.label}</span><code>{port.type}</code></div>) : <small>None</small>}<strong className="spn-graph-port-heading">OUTPUTS</strong>{definition.outputs.length ? definition.outputs.map((port) => <div className="spn-graph-inspector-row" key={port.id}><span>{port.label}{outputs[node.id]?.[port.id] !== undefined ? ` · ${format(outputs[node.id][port.id])}` : ''}</span><code>{port.type}</code></div>) : <small>None</small>}</section>
  </div>
}
function format(value: GraphValue):string { if(Array.isArray(value)){if(value.every(item=>typeof item==='object'&&item!==null&&'quantityKind'in item))return formatQuantityList(value as import('../domain/quantities').EngineeringQuantity[]);return `[${value.map(format).join(', ')}]`}if(typeof value==='object'&&value!==null&&'quantityKind'in value)return formatQuantity(value);if(typeof value==='object'&&value!==null&&'domainType'in value){const material=value as import('../domain/types').MaterialValue;const props=Object.entries(material.properties).map(([key,q])=>`${key} ${formatQuantity(q)}`).join(', ');return `${material.domainType} ${material.name}${props?` · ${props}`:''}`}return String(value) }
